"""Registry entries for the postprocessing pipeline family."""

from __future__ import annotations

from flytetest.registry._types import (
    InterfaceField,
    RegistryCompatibilityMetadata,
    RegistryEntry,
)


POSTPROCESSING_ENTRIES: tuple[RegistryEntry, ...] = (
    RegistryEntry(
        name='annotation_repeat_filtering',
        category='workflow',
        description='Repeat-filtering workflow that starts from the PASA-updated GFF3 boundary plus an external RepeatMasker `.out` file, runs explicit RepeatMasker conversion, gffread protein extraction, funannotate overlap filtering, repeat blasting, deterministic removal transforms, and collects a manifest-bearing repeat-free results bundle.',
        inputs=(
            InterfaceField('pasa_update_results', 'Dir', 'PASA post-EVM refinement results directory from annotation_refinement_pasa.'),
            InterfaceField('repeatmasker_out', 'File', 'RepeatMasker `.out` file supplied as the upstream repeat-mask annotation source for this stage.'),
            InterfaceField('funannotate_db_path', 'str', 'Local path to the funannotate database root used for RepeatBlast.'),
            InterfaceField('rmout_to_gff3_script', 'str', 'rmOutToGFF3.pl path or executable name.'),
            InterfaceField('gffread_binary', 'str', 'gffread path or executable name.'),
            InterfaceField('funannotate_python', 'str', 'Python interpreter used to call the funannotate library wrappers shown in the notes.'),
            InterfaceField('repeat_filter_sif', 'str', 'Optional Apptainer/Singularity image path for the repeat-filtering toolchain.'),
            InterfaceField('min_protlen', 'int', 'Minimum protein length passed to funannotate RemoveBadModels.'),
            InterfaceField('repeat_blast_cpu', 'int', 'CPU count passed to funannotate RepeatBlast.'),
            InterfaceField('repeat_blast_evalue', 'float', 'E-value threshold passed to funannotate RepeatBlast.'),
        ),
        outputs=(
            InterfaceField('results_dir', 'Dir', 'Timestamped repeat-filtering results directory containing repeatmasker.gff3, repeatmasker.bed, intermediate filtered GFF3/protein FASTA files, final repeat-free outputs, and run_manifest.json.'),
        ),
        tags=('workflow', 'repeat-filtering', 'cleanup', 'funannotate'),
        compatibility=RegistryCompatibilityMetadata(
            biological_stage='repeat filtering and annotation cleanup',
            accepted_planner_types=('ConsensusAnnotation',),
            produced_planner_types=('ConsensusAnnotation', 'QualityAssessmentTarget',),
            reusable_as_reference=True,
            execution_defaults={
            'profile': 'local',
            'result_manifest': 'run_manifest.json',
            'resources': {'cpu': '16', 'memory': '64Gi', 'execution_class': 'local'},
            'slurm_resource_hints': {'cpu': '16', 'memory': '64Gi', 'walltime': '12:00:00'},
        },
            supported_execution_profiles=('local', 'slurm',),
            synthesis_eligible=True,
            composition_constraints=('Starts from the PASA-updated sorted GFF3 boundary plus a user-supplied RepeatMasker .out file.',),
            pipeline_family='annotation',
            pipeline_stage_order=9,
        ),
    ),
    RegistryEntry(
        name='annotation_qc_busco',
        category='workflow',
        description='BUSCO-based annotation quality-assessment workflow that consumes the repeat-filtered protein FASTA boundary, runs one BUSCO task per selected lineage, and collects a manifest-bearing quality-assessment bundle.',
        inputs=(
            InterfaceField('repeat_filter_results', 'Dir', 'Repeat-filtering results directory from annotation_repeat_filtering containing the final repeat-free protein FASTA that BUSCO treats as the quality-assessment input.'),
            InterfaceField('busco_lineages_text', 'str', 'Comma-separated BUSCO lineage list. The workflow currently defaults to the eukaryota, metazoa, insecta, arthropoda, and diptera lineages.'),
            InterfaceField('busco_sif', 'str', 'Optional Apptainer/Singularity image path for BUSCO.'),
            InterfaceField('busco_cpu', 'int', 'CPU count passed to each BUSCO lineage run.'),
        ),
        outputs=(
            InterfaceField('results_dir', 'Dir', 'Timestamped BUSCO quality-assessment results directory containing copied lineage runs, busco_summary.tsv, and run_manifest.json.'),
        ),
        tags=('workflow', 'busco', 'annotation-qc', 'proteins'),
        showcase_module='flytetest.workflows.functional',
        compatibility=RegistryCompatibilityMetadata(
            biological_stage='BUSCO annotation quality assessment',
            accepted_planner_types=('QualityAssessmentTarget',),
            produced_planner_types=('QualityAssessmentTarget',),
            reusable_as_reference=True,
            execution_defaults={
                'profile': 'local',
                'result_manifest': 'run_manifest.json',
                'resources': {'cpu': '16', 'memory': '64Gi', 'execution_class': 'local'},
                'slurm_resource_hints': {'cpu': '16', 'memory': '64Gi', 'walltime': '04:00:00'},
                'runtime_images': {'busco_sif': 'data/images/busco_v6.0.0_cv1.sif'},
                'tool_databases': {'busco_lineage_dir': 'data/busco/lineages/eukaryota_odb10'},
                'module_loads': ('python/3.11.9', 'apptainer/1.4.1'),
            },
            supported_execution_profiles=('local', 'slurm',),
            synthesis_eligible=True,
            composition_constraints=('Consumes the repeat-filtered protein FASTA boundary as the current QC target and does not run EggNOG, AGAT, or submission prep.',),
            pipeline_family='annotation',
            pipeline_stage_order=10,
        ),
    ),
    RegistryEntry(
        name='annotation_functional_eggnog',
        category='workflow',
        description='EggNOG functional-annotation workflow that consumes the repeat-filtered protein FASTA boundary after quality assessment, runs EggNOG-mapper with an explicit database directory, and collects a manifest-bearing annotated GFF3 bundle.',
        inputs=(
            InterfaceField('repeat_filter_results', 'Dir', 'Repeat-filtering results directory from annotation_repeat_filtering containing the final repeat-free proteins FASTA and GFF3 that the planner treats as the current quality-assessed source bundle.'),
            InterfaceField('eggnog_data_dir', 'str', 'Local EggNOG database directory staged outside the repo milestone.'),
            InterfaceField('eggnog_sif', 'str', 'Optional Apptainer/Singularity image path for EggNOG-mapper.'),
            InterfaceField('eggnog_cpu', 'int', 'CPU count passed to EggNOG-mapper.'),
            InterfaceField('eggnog_database', 'str', 'EggNOG database or taxonomic scope passed with `-d`.'),
        ),
        outputs=(
            InterfaceField('results_dir', 'Dir', 'Timestamped EggNOG results directory containing copied source boundary files, EggNOG outputs, and run_manifest.json.'),
        ),
        tags=('workflow', 'eggnog', 'functional-annotation', 'proteins'),
        showcase_module='flytetest.workflows.eggnog',
        compatibility=RegistryCompatibilityMetadata(
            biological_stage='EggNOG functional annotation',
            accepted_planner_types=('QualityAssessmentTarget',),
            produced_planner_types=('QualityAssessmentTarget',),
            reusable_as_reference=True,
            execution_defaults={
            'profile': 'local',
            'result_manifest': 'run_manifest.json',
            'resources': {'cpu': '16', 'memory': '64Gi', 'execution_class': 'local'},
            'slurm_resource_hints': {'cpu': '16', 'memory': '64Gi', 'walltime': '04:00:00'},
        },
            supported_execution_profiles=('local', 'slurm',),
            synthesis_eligible=True,
            composition_constraints=('Consumes the repeat-filtered protein FASTA boundary after BUSCO-style quality assessment and keeps AGAT and submission prep deferred.',),
            pipeline_family='annotation',
            pipeline_stage_order=11,
        ),
    ),
    RegistryEntry(
        name='annotation_postprocess_agat',
        category='workflow',
        description='AGAT post-processing workflow that consumes the EggNOG-annotated GFF3 bundle after quality assessment and collects the statistics slice in a manifest-bearing results directory.',
        inputs=(
            InterfaceField('eggnog_results', 'Dir', 'EggNOG results directory from annotation_functional_eggnog containing the annotated GFF3 boundary that serves as the post-quality-assessment input for AGAT statistics.'),
            InterfaceField('annotation_fasta_path', 'str', 'Optional companion FASTA path for the AGAT statistics command.'),
            InterfaceField('agat_sif', 'str', 'Optional Apptainer/Singularity image path for AGAT.'),
        ),
        outputs=(
            InterfaceField('results_dir', 'Dir', 'Timestamped AGAT results directory containing copied source files, AGAT statistics output, and run_manifest.json.'),
        ),
        tags=('workflow', 'agat', 'post-processing', 'statistics'),
        showcase_module='flytetest.workflows.agat',
        compatibility=RegistryCompatibilityMetadata(
            biological_stage='AGAT post-processing',
            accepted_planner_types=('QualityAssessmentTarget',),
            produced_planner_types=('QualityAssessmentTarget',),
            reusable_as_reference=True,
            execution_defaults={
            'profile': 'local',
            'result_manifest': 'run_manifest.json',
            'resources': {'cpu': '8', 'memory': '32Gi', 'execution_class': 'local'},
            'slurm_resource_hints': {'cpu': '4', 'memory': '16Gi', 'walltime': '00:30:00'},
        },
            supported_execution_profiles=('local', 'slurm',),
            synthesis_eligible=True,
            composition_constraints=('Consumes the EggNOG-annotated GFF3 boundary after quality assessment and keeps AGAT conversion, cleanup, and table2asn as separate follow-on slices.',),
            pipeline_family='annotation',
            pipeline_stage_order=12,
        ),
    ),
    RegistryEntry(
        name='annotation_postprocess_agat_conversion',
        category='workflow',
        description='AGAT conversion workflow that consumes the EggNOG-annotated GFF3 bundle after quality assessment and collects the normalized GFF3 slice in a manifest-bearing results directory.',
        inputs=(
            InterfaceField('eggnog_results', 'Dir', 'EggNOG results directory from annotation_functional_eggnog containing the annotated GFF3 boundary that serves as the post-quality-assessment input for AGAT conversion.'),
            InterfaceField('agat_sif', 'str', 'Optional Apptainer/Singularity image path for AGAT.'),
        ),
        outputs=(
            InterfaceField('results_dir', 'Dir', 'Timestamped AGAT results directory containing copied source files, the converted GFF3, and run_manifest.json.'),
        ),
        tags=('workflow', 'agat', 'post-processing', 'conversion'),
        showcase_module='flytetest.workflows.agat',
        compatibility=RegistryCompatibilityMetadata(
            biological_stage='AGAT post-processing',
            accepted_planner_types=('QualityAssessmentTarget',),
            produced_planner_types=('QualityAssessmentTarget',),
            reusable_as_reference=True,
            execution_defaults={
            'profile': 'local',
            'result_manifest': 'run_manifest.json',
            'resources': {'cpu': '8', 'memory': '32Gi', 'execution_class': 'local'},
            'slurm_resource_hints': {'cpu': '4', 'memory': '16Gi', 'walltime': '00:30:00'},
        },
            supported_execution_profiles=('local', 'slurm',),
            synthesis_eligible=True,
            composition_constraints=('Consumes the EggNOG-annotated GFF3 boundary after quality assessment, uses the AGAT conversion command family explicitly, and keeps cleanup as a separate follow-on slice before table2asn.',),
            pipeline_family='annotation',
            pipeline_stage_order=13,
        ),
    ),
    RegistryEntry(
        name='annotation_postprocess_agat_cleanup',
        category='workflow',
        description='AGAT cleanup workflow that consumes the AGAT conversion bundle after quality assessment and collects the deterministic cleaned GFF3 slice without running table2asn.',
        inputs=(
            InterfaceField('agat_conversion_results', 'Dir', 'AGAT conversion results directory from annotation_postprocess_agat_conversion containing the converted GFF3 boundary that serves as the cleanup input after quality assessment.'),
        ),
        outputs=(
            InterfaceField('results_dir', 'Dir', 'Timestamped AGAT cleanup results directory containing copied source files, the cleaned GFF3, cleanup summary, and run_manifest.json.'),
        ),
        tags=('workflow', 'agat', 'post-processing', 'cleanup'),
        showcase_module='flytetest.workflows.agat',
        compatibility=RegistryCompatibilityMetadata(
            biological_stage='AGAT post-processing',
            accepted_planner_types=('QualityAssessmentTarget',),
            produced_planner_types=('QualityAssessmentTarget',),
            reusable_as_reference=True,
            execution_defaults={
            'profile': 'local',
            'result_manifest': 'run_manifest.json',
            'resources': {'cpu': '8', 'memory': '32Gi', 'execution_class': 'local'},
            'slurm_resource_hints': {'cpu': '8', 'memory': '32Gi', 'walltime': '01:00:00'},
        },
            supported_execution_profiles=('local', 'slurm',),
            synthesis_eligible=True,
            composition_constraints=('Consumes the AGAT conversion GFF3 boundary after quality assessment, applies the deterministic cleanup rules, and keeps table2asn deferred.',),
            pipeline_family='annotation',
            pipeline_stage_order=14,
        ),
    ),
    RegistryEntry(
        name='annotation_postprocess_table2asn',
        category='workflow',
        description='table2asn submission workflow that consumes the AGAT cleanup bundle and produces an NCBI .sqn submission file alongside validation artefacts.',
        inputs=(
            InterfaceField('agat_cleanup_results', 'Dir', 'AGAT cleanup results directory from annotation_postprocess_agat_cleanup containing the cleaned GFF3 that serves as the -f input to table2asn.'),
            InterfaceField('genome_fasta', 'str', 'Path to the repeat-masked genome FASTA used as the -i input to table2asn.'),
            InterfaceField('submission_template', 'str', 'Path to the NCBI .sbt template file generated on submit.ncbi.nlm.nih.gov (-t).'),
            InterfaceField('locus_tag_prefix', 'str', 'BioProject locus-tag prefix assigned by NCBI (-locus-tag-prefix). Omitted from the command when empty.'),
            InterfaceField('organism_annotation', 'str', 'NCBI organism annotation string such as [organism=Foo bar][isolate=X] (-j). Omitted when empty.'),
            InterfaceField('table2asn_binary', 'str', "Name or path of the table2asn executable. Defaults to 'table2asn'."),
            InterfaceField('table2asn_sif', 'str', 'Optional Apptainer/Singularity image path for table2asn.'),
        ),
        outputs=(
            InterfaceField('results_dir', 'Dir', 'Timestamped table2asn results directory containing the .sqn submission file, validation artefacts, and run_manifest.json.'),
        ),
        tags=('workflow', 'table2asn', 'ncbi', 'submission', 'post-processing'),
        showcase_module='flytetest.workflows.agat',
        compatibility=RegistryCompatibilityMetadata(
            biological_stage='NCBI submission preparation',
            accepted_planner_types=('QualityAssessmentTarget',),
            produced_planner_types=('QualityAssessmentTarget',),
            reusable_as_reference=True,
            execution_defaults={
            'profile': 'local',
            'result_manifest': 'run_manifest.json',
            'resources': {'cpu': '4', 'memory': '16Gi', 'execution_class': 'local'},
            'slurm_resource_hints': {'cpu': '4', 'memory': '16Gi', 'walltime': '02:00:00'},
        },
            supported_execution_profiles=('local', 'slurm',),
            synthesis_eligible=True,
            composition_constraints=('Consumes the AGAT cleanup GFF3 boundary and runs table2asn to produce an NCBI .sqn submission file. Requires a valid NCBI .sbt submission template and a BioProject locus-tag prefix.',),
            pipeline_family='annotation',
            pipeline_stage_order=15,
        ),
    ),
    RegistryEntry(
        name='repeatmasker_out_to_bed',
        category='task',
        description='Convert one external RepeatMasker `.out` file into the note-shaped RepeatMasker GFF3 plus three-column BED used for later overlap filtering.',
        inputs=(
            InterfaceField('repeatmasker_out', 'File', 'RepeatMasker `.out` file produced upstream of this milestone.'),
            InterfaceField('rmout_to_gff3_script', 'str', 'rmOutToGFF3.pl path or executable name.'),
            InterfaceField('repeat_filter_sif', 'str', 'Optional Apptainer/Singularity image path for the repeat-filtering toolchain.'),
        ),
        outputs=(
            InterfaceField('repeatmasker_dir', 'Dir', 'Directory containing the staged RepeatMasker `.out`, converted repeatmasker.gff3, repeatmasker.bed, and run_manifest.json.'),
        ),
        tags=('repeat-filtering', 'repeatmasker', 'conversion', 'bed'),
    ),
    RegistryEntry(
        name='gffread_proteins',
        category='task',
        description='Extract proteins from one annotation GFF3 with gffread and emit a second period-stripped FASTA for the later funannotate repeat blast step.',
        inputs=(
            InterfaceField('annotation_gff3', 'File', 'Annotation GFF3 to translate into proteins.'),
            InterfaceField('genome_fasta', 'File', 'Reference genome FASTA passed to gffread with -g.'),
            InterfaceField('protein_output_stem', 'str', 'Filename stem used for the emitted protein FASTA files.'),
            InterfaceField('gffread_binary', 'str', 'gffread path or executable name.'),
            InterfaceField('repeat_filter_sif', 'str', 'Optional Apptainer/Singularity image path for the repeat-filtering toolchain.'),
        ),
        outputs=(
            InterfaceField('proteins_dir', 'Dir', 'Directory containing `<stem>.proteins.fa`, `<stem>.proteins.no_periods.fa`, and run_manifest.json.'),
        ),
        tags=('repeat-filtering', 'gffread', 'proteins', 'diamond-ready'),
        showcase_module='flytetest.tasks.filtering',
    ),
    RegistryEntry(
        name='funannotate_remove_bad_models',
        category='task',
        description='Run the note-shaped funannotate overlap filter against the current annotation, protein FASTA, and RepeatMasker BED to emit a clean GFF3 plus the overlap-removal list.',
        inputs=(
            InterfaceField('annotation_gff3', 'File', 'Current annotation GFF3 being overlap-filtered.'),
            InterfaceField('proteins_fasta', 'File', 'Protein FASTA, typically the period-stripped gffread output for the same annotation.'),
            InterfaceField('repeatmasker_bed', 'File', 'RepeatMasker BED produced by repeatmasker_out_to_bed.'),
            InterfaceField('clean_output_name', 'str', 'Filename used for the clean GFF3 emitted by the funannotate overlap stage.'),
            InterfaceField('funannotate_python', 'str', 'Python interpreter used to call the funannotate library wrapper shown in the notes.'),
            InterfaceField('repeat_filter_sif', 'str', 'Optional Apptainer/Singularity image path for the repeat-filtering toolchain.'),
            InterfaceField('min_protlen', 'int', 'Minimum protein length passed to funannotate RemoveBadModels.'),
        ),
        outputs=(
            InterfaceField('overlap_filter_dir', 'Dir', 'Directory containing the clean GFF3, the overlap-removal list emitted by funannotate, and run_manifest.json.'),
        ),
        tags=('repeat-filtering', 'funannotate', 'overlap', 'cleanup'),
    ),
    RegistryEntry(
        name='remove_overlap_repeat_models',
        category='task',
        description='Apply the overlap-removal list to the current annotation GFF3 as a deterministic local transform instead of a shell `grep -vFf` helper.',
        inputs=(
            InterfaceField('annotation_gff3', 'File', 'Current annotation GFF3.'),
            InterfaceField('models_to_remove', 'File', 'Overlap-removal list produced by funannotate_remove_bad_models.'),
            InterfaceField('output_name', 'str', 'Filename used for the filtered GFF3 output.'),
        ),
        outputs=(
            InterfaceField('filtered_dir', 'Dir', 'Directory containing the overlap-filtered GFF3 plus run_manifest.json.'),
        ),
        tags=('repeat-filtering', 'filtering', 'overlap', 'gff3'),
    ),
    RegistryEntry(
        name='funannotate_repeat_blast',
        category='task',
        description='Run the note-shaped funannotate repeat blast against the explicit local funannotate database root and emit repeat.dmnd.blast.txt.',
        inputs=(
            InterfaceField('proteins_fasta', 'File', 'Protein FASTA, typically the period-stripped proteins from the overlap-filtered annotation.'),
            InterfaceField('funannotate_db_path', 'str', 'Local path to the funannotate database root used by RepeatBlast.'),
            InterfaceField('funannotate_python', 'str', 'Python interpreter used to call the funannotate library wrapper shown in the notes.'),
            InterfaceField('repeat_filter_sif', 'str', 'Optional Apptainer/Singularity image path for the repeat-filtering toolchain.'),
            InterfaceField('repeat_blast_cpu', 'int', 'CPU count passed to funannotate RepeatBlast.'),
            InterfaceField('repeat_blast_evalue', 'float', 'E-value threshold passed to funannotate RepeatBlast.'),
        ),
        outputs=(
            InterfaceField('repeat_blast_dir', 'Dir', 'Directory containing repeat.dmnd.blast.txt and run_manifest.json.'),
        ),
        tags=('repeat-filtering', 'funannotate', 'blast', 'repeats'),
    ),
    RegistryEntry(
        name='remove_repeat_blast_hits',
        category='task',
        description='Remove repeat-blast-hit models from the current annotation GFF3 using the notes-shaped Parent/ID filtering rules as a deterministic transform.',
        inputs=(
            InterfaceField('annotation_gff3', 'File', 'Current overlap-filtered annotation GFF3.'),
            InterfaceField('repeat_blast_results', 'Dir', 'Directory produced by funannotate_repeat_blast.'),
            InterfaceField('output_name', 'str', 'Filename used for the final repeat-filtered GFF3 output.'),
        ),
        outputs=(
            InterfaceField('filtered_dir', 'Dir', 'Directory containing the blast-filtered GFF3 plus run_manifest.json.'),
        ),
        tags=('repeat-filtering', 'filtering', 'blast', 'gff3'),
    ),
    RegistryEntry(
        name='collect_repeat_filter_results',
        category='task',
        description='Collect repeat-filtering stage outputs into a manifest-bearing results bundle rooted in the PASA-updated boundary and ending at final repeat-free GFF3 plus protein FASTA outputs.',
        inputs=(
            InterfaceField('pasa_update_results', 'Dir', 'PASA post-EVM refinement results directory from annotation_refinement_pasa.'),
            InterfaceField('repeatmasker_conversion', 'Dir', 'Directory produced by repeatmasker_out_to_bed.'),
            InterfaceField('initial_proteins', 'Dir', 'Directory produced by the first gffread_proteins call against the PASA-updated GFF3.'),
            InterfaceField('overlap_filter', 'Dir', 'Directory produced by funannotate_remove_bad_models.'),
            InterfaceField('overlap_removed', 'Dir', 'Directory produced by remove_overlap_repeat_models.'),
            InterfaceField('bed_filtered_proteins', 'Dir', 'Directory produced by the second gffread_proteins call after overlap filtering.'),
            InterfaceField('repeat_blast', 'Dir', 'Directory produced by funannotate_repeat_blast.'),
            InterfaceField('blast_removed', 'Dir', 'Directory produced by remove_repeat_blast_hits.'),
            InterfaceField('final_proteins', 'Dir', 'Directory produced by the final gffread_proteins call after repeat blast filtering.'),
        ),
        outputs=(
            InterfaceField('results_dir', 'Dir', 'Timestamped repeat-filtering results directory containing copied stage outputs, final repeat-free GFF3/protein FASTA files, and run_manifest.json.'),
        ),
        tags=('repeat-filtering', 'results', 'manifest', 'cleanup'),
    ),
    RegistryEntry(
        name='busco_assess_proteins',
        category='task',
        description='Run one BUSCO protein-mode assessment against one selected lineage dataset downstream of repeat filtering.',
        inputs=(
            InterfaceField('proteins_fasta', 'File', 'Repeat-filtered protein FASTA used as the BUSCO input.'),
            InterfaceField('lineage_dataset', 'str', 'BUSCO lineage dataset identifier or local lineage path passed with `-l`; use `auto-lineage` to omit `-l` for fixture smoke runs.'),
            InterfaceField('busco_sif', 'str', 'Optional Apptainer/Singularity image path for BUSCO.'),
            InterfaceField('busco_cpu', 'int', 'CPU count passed to BUSCO with `-c`.'),
            InterfaceField('busco_mode', 'str', 'BUSCO mode passed with `-m`; this milestone uses `prot`.'),
        ),
        outputs=(
            InterfaceField('run_dir', 'Dir', 'Directory containing one BUSCO lineage run plus run_manifest.json.'),
        ),
        tags=('busco', 'annotation-qc', 'proteins', 'lineage'),
        showcase_module='flytetest.tasks.functional',
        compatibility=RegistryCompatibilityMetadata(
            biological_stage='BUSCO fixture and lineage assessment',
            pipeline_family='annotation',
            produced_planner_types=('Dir',),
            reusable_as_reference=True,
            execution_defaults={
                'profile': 'local',
                'result_manifest': 'run_manifest.json',
                'resources': {'cpu': '2', 'memory': '8Gi', 'execution_class': 'local'},
                'slurm_resource_hints': {'cpu': '4', 'memory': '16Gi', 'walltime': '01:00:00'},
                'runtime_images': {'busco_sif': 'data/images/busco_v6.0.0_cv1.sif'},
                'tool_databases': {'busco_lineage_dir': 'data/busco/lineages/eukaryota_odb10'},
                'module_loads': ('python/3.11.9', 'apptainer/1.4.1'),
            },
            supported_execution_profiles=('local', 'slurm',),
            composition_constraints=('The M18 fixture path uses genome mode against the upstream BUSCO eukaryota test FASTA while the annotation QC workflow still runs BUSCO on repeat-filtered proteins.',),
        ),
    ),
    RegistryEntry(
        name='collect_busco_results',
        category='task',
        description='Collect BUSCO lineage runs into a manifest-bearing annotation-QC bundle rooted in the repeat-filtered protein FASTA boundary.',
        inputs=(
            InterfaceField('repeat_filter_results', 'Dir', 'Repeat-filtering results directory containing the final repeat-free proteins FASTA.'),
            InterfaceField('busco_runs', 'list[Dir]', 'One or more BUSCO lineage run directories to collect.'),
            InterfaceField('busco_lineages_text', 'str', 'Comma-separated lineage list recorded in the collector manifest and summary table.'),
        ),
        outputs=(
            InterfaceField('results_dir', 'Dir', 'Timestamped BUSCO QC results directory containing copied lineage runs, busco_summary.tsv, and run_manifest.json.'),
        ),
        tags=('busco', 'annotation-qc', 'results', 'manifest'),
    ),
    RegistryEntry(
        name='eggnog_map',
        category='task',
        description='Run EggNOG-mapper on the repeat-filtered protein FASTA boundary, preserve a deterministic tx2gene bridge, and propagate gene names into a reviewable annotated GFF3.',
        inputs=(
            InterfaceField('repeat_filter_results', 'Dir', 'Repeat-filtering results directory containing the final repeat-free proteins FASTA and GFF3.'),
            InterfaceField('eggnog_data_dir', 'str', 'Local EggNOG database directory staged outside the repo milestone.'),
            InterfaceField('eggnog_sif', 'str', 'Optional Apptainer/Singularity image path for EggNOG-mapper.'),
            InterfaceField('eggnog_cpu', 'int', 'CPU count passed to EggNOG-mapper with `--cpu`.'),
            InterfaceField('eggnog_database', 'str', 'EggNOG taxonomic database or scope passed with `-d`.'),
            InterfaceField('eggnog_mode', 'str', 'EggNOG mode passed with `-m`; this milestone uses `hmmer`.'),
        ),
        outputs=(
            InterfaceField('eggnog_run_dir', 'Dir', 'Directory containing EggNOG-mapper outputs, tx2gene.tsv, annotated GFF3, and run_manifest.json.'),
        ),
        tags=('eggnog', 'functional-annotation', 'proteins', 'gff3'),
    ),
    RegistryEntry(
        name='collect_eggnog_results',
        category='task',
        description='Collect EggNOG functional-annotation outputs into a manifest-bearing results bundle rooted in the repeat-filtered protein FASTA boundary.',
        inputs=(
            InterfaceField('repeat_filter_results', 'Dir', 'Repeat-filtering results directory containing the final repeat-free proteins FASTA and GFF3.'),
            InterfaceField('eggnog_run', 'Dir', 'EggNOG-mapper run directory to collect.'),
        ),
        outputs=(
            InterfaceField('results_dir', 'Dir', 'Timestamped EggNOG results directory containing copied source boundary files, EggNOG outputs, and run_manifest.json.'),
        ),
        tags=('eggnog', 'functional-annotation', 'results', 'manifest'),
    ),
    RegistryEntry(
        name='agat_statistics',
        category='task',
        description='Run AGAT statistics on the EggNOG-annotated GFF3 bundle and collect the resulting summary files in a manifest-bearing results directory.',
        inputs=(
            InterfaceField('eggnog_results', 'Dir', 'EggNOG results directory containing the annotated GFF3 boundary and run manifest.'),
            InterfaceField('annotation_fasta_path', 'str', 'Optional companion FASTA path for the AGAT statistics command.'),
            InterfaceField('agat_sif', 'str', 'Optional Apptainer/Singularity image path for AGAT.'),
        ),
        outputs=(
            InterfaceField('results_dir', 'Dir', 'Timestamped AGAT results directory containing the EggNOG-annotated GFF3 boundary, AGAT statistics output, and run_manifest.json.'),
        ),
        tags=('agat', 'post-processing', 'statistics', 'gff3'),
    ),
    RegistryEntry(
        name='agat_convert_sp_gxf2gxf',
        category='task',
        description='Run AGAT conversion on the EggNOG-annotated GFF3 bundle with `agat_convert_sp_gxf2gxf.pl` and collect the normalized GFF3 into a manifest-bearing results directory.',
        inputs=(
            InterfaceField('eggnog_results', 'Dir', 'EggNOG results directory containing the annotated GFF3 boundary and run manifest.'),
            InterfaceField('agat_sif', 'str', 'Optional Apptainer/Singularity image path for AGAT.'),
        ),
        outputs=(
            InterfaceField('results_dir', 'Dir', 'Timestamped AGAT results directory containing the EggNOG-annotated GFF3 boundary, converted GFF3, and run_manifest.json.'),
        ),
        tags=('agat', 'post-processing', 'conversion', 'gff3'),
    ),
    RegistryEntry(
        name='agat_cleanup_gff3',
        category='task',
        description='Apply the deterministic post-AGAT GFF3 attribute cleanup to an AGAT conversion bundle and collect the cleaned GFF3 into a manifest-bearing results directory.',
        inputs=(
            InterfaceField('agat_conversion_results', 'Dir', 'AGAT conversion results directory containing the converted GFF3 boundary and run manifest.'),
        ),
        outputs=(
            InterfaceField('results_dir', 'Dir', 'Timestamped AGAT cleanup results directory containing the converted source GFF3, cleaned GFF3, cleanup summary, and run_manifest.json.'),
        ),
        tags=('agat', 'post-processing', 'cleanup', 'gff3'),
    ),
)
