"""Registry entries for the variant_calling pipeline family."""

from __future__ import annotations

from flytetest.registry._types import (
    InterfaceField,
    RegistryCompatibilityMetadata,
    RegistryEntry,
)

VARIANT_CALLING_ENTRIES: tuple[RegistryEntry, ...] = (
    RegistryEntry(
        name="create_sequence_dictionary",
        category="task",
        description="Emit a GATK4 sequence dictionary (.dict) next to a reference FASTA via CreateSequenceDictionary.",
        inputs=(
            InterfaceField("reference_fasta", "File", "Reference genome FASTA."),
            InterfaceField("gatk_sif", "str", "Optional Apptainer/Singularity image path for GATK4."),
        ),
        outputs=(
            InterfaceField("sequence_dict", "File", "GATK4 sequence dictionary (.dict) file emitted next to the reference FASTA."),
        ),
        tags=("variant_calling", "gatk4", "reference_prep"),
        compatibility=RegistryCompatibilityMetadata(
            biological_stage="GATK4 reference sequence dictionary",
            accepted_planner_types=("ReferenceGenome",),
            produced_planner_types=(),
            reusable_as_reference=True,
            execution_defaults={
                "profile": "local",
                "result_manifest": "run_manifest.json",
                "resources": {"cpu": "1", "memory": "4Gi", "execution_class": "local"},
                "slurm_resource_hints": {"cpu": "1", "memory": "4Gi", "walltime": "00:30:00"},
                "runtime_images": {"gatk_sif": "data/images/gatk4.sif"},
                "module_loads": ("python/3.11.9", "apptainer/1.4.1"),
            },
            supported_execution_profiles=("local", "slurm"),
            synthesis_eligible=True,
            composition_constraints=(
                "Requires a reference genome FASTA; emits the sequence dictionary downstream tools depend on.",
            ),
            pipeline_family="variant_calling",
            pipeline_stage_order=1,
        ),
    ),
    RegistryEntry(
        name="index_feature_file",
        category="task",
        description="Emit a GATK4 feature-file index (.idx or .tbi) next to a VCF/GVCF via IndexFeatureFile.",
        inputs=(
            InterfaceField("vcf", "File", "VCF or GVCF to index."),
            InterfaceField("gatk_sif", "str", "Optional Apptainer/Singularity image path for GATK4."),
        ),
        outputs=(
            InterfaceField("feature_index", "File", "GATK4 index (.idx for plain VCF, .tbi for .vcf.gz) written next to the input VCF."),
        ),
        tags=("variant_calling", "gatk4", "reference_prep"),
        compatibility=RegistryCompatibilityMetadata(
            biological_stage="GATK4 feature-file indexing",
            accepted_planner_types=("KnownSites",),
            produced_planner_types=(),
            reusable_as_reference=True,
            execution_defaults={
                "profile": "local",
                "result_manifest": "run_manifest.json",
                "resources": {"cpu": "1", "memory": "4Gi", "execution_class": "local"},
                "slurm_resource_hints": {"cpu": "1", "memory": "4Gi", "walltime": "00:30:00"},
                "runtime_images": {"gatk_sif": "data/images/gatk4.sif"},
                "module_loads": ("python/3.11.9", "apptainer/1.4.1"),
            },
            supported_execution_profiles=("local", "slurm"),
            synthesis_eligible=True,
            composition_constraints=(
                "Requires a VCF or GVCF; emits the index file BQSR and downstream steps depend on.",
            ),
            pipeline_family="variant_calling",
            pipeline_stage_order=2,
        ),
    ),
    RegistryEntry(
        name="base_recalibrator",
        category="task",
        description="Generate a GATK4 BQSR recalibration table via BaseRecalibrator.",
        inputs=(
            InterfaceField("reference_fasta", "File", "Reference genome FASTA."),
            InterfaceField("aligned_bam", "File", "Coordinate-sorted, duplicate-marked BAM."),
            InterfaceField("known_sites", "list[File]", "Indexed known-sites VCF(s) for BQSR."),
            InterfaceField("sample_id", "str", "Sample identifier used to name the output table."),
            InterfaceField("gatk_sif", "str", "Optional Apptainer/Singularity image path for GATK4."),
        ),
        outputs=(
            InterfaceField("bqsr_report", "File", "GATK4 BQSR recalibration table (.table)."),
        ),
        tags=("variant_calling", "gatk4", "bqsr"),
        compatibility=RegistryCompatibilityMetadata(
            biological_stage="GATK4 base quality score recalibration report",
            accepted_planner_types=("ReferenceGenome", "AlignmentSet", "KnownSites"),
            produced_planner_types=(),
            reusable_as_reference=False,
            execution_defaults={
                "profile": "local",
                "result_manifest": "run_manifest.json",
                "resources": {"cpu": "4", "memory": "16Gi", "execution_class": "local"},
                "slurm_resource_hints": {"cpu": "8", "memory": "32Gi", "walltime": "06:00:00"},
                "runtime_images": {"gatk_sif": "data/images/gatk4.sif"},
                "module_loads": ("python/3.11.9", "apptainer/1.4.1"),
            },
            supported_execution_profiles=("local", "slurm"),
            synthesis_eligible=True,
            composition_constraints=(
                "Requires coordinate-sorted dedup'd BAM + reference + \u22651 indexed known-sites VCF.",
            ),
            pipeline_family="variant_calling",
            pipeline_stage_order=3,
        ),
    ),
    RegistryEntry(
        name="apply_bqsr",
        category="task",
        description="Apply a GATK4 BQSR recalibration table to an aligned BAM via ApplyBQSR.",
        inputs=(
            InterfaceField("reference_fasta", "File", "Reference genome FASTA."),
            InterfaceField("aligned_bam", "File", "Coordinate-sorted, duplicate-marked BAM."),
            InterfaceField("bqsr_report", "File", "BQSR recalibration table from base_recalibrator."),
            InterfaceField("sample_id", "str", "Sample identifier used to name the output BAM."),
            InterfaceField("gatk_sif", "str", "Optional Apptainer/Singularity image path for GATK4."),
        ),
        outputs=(
            InterfaceField("recalibrated_bam", "File", "Recalibrated BAM produced by GATK4 ApplyBQSR."),
        ),
        tags=("variant_calling", "gatk4", "bqsr"),
        compatibility=RegistryCompatibilityMetadata(
            biological_stage="GATK4 apply base quality score recalibration",
            accepted_planner_types=("ReferenceGenome", "AlignmentSet"),
            produced_planner_types=("AlignmentSet",),
            reusable_as_reference=False,
            execution_defaults={
                "profile": "local",
                "result_manifest": "run_manifest.json",
                "resources": {"cpu": "4", "memory": "16Gi", "execution_class": "local"},
                "slurm_resource_hints": {"cpu": "8", "memory": "32Gi", "walltime": "06:00:00"},
                "runtime_images": {"gatk_sif": "data/images/gatk4.sif"},
                "module_loads": ("python/3.11.9", "apptainer/1.4.1"),
            },
            supported_execution_profiles=("local", "slurm"),
            synthesis_eligible=True,
            composition_constraints=(
                "Requires coordinate-sorted dedup'd BAM + reference + BQSR table from base_recalibrator.",
            ),
            pipeline_family="variant_calling",
            pipeline_stage_order=4,
        ),
    ),
    RegistryEntry(
        name="haplotype_caller",
        category="task",
        description="Call per-sample germline variants in GVCF mode via GATK4 HaplotypeCaller.",
        inputs=(
            InterfaceField("reference_fasta", "File", "Reference genome FASTA."),
            InterfaceField("aligned_bam", "File", "Coordinate-sorted, dedup'd, BQSR-recalibrated BAM."),
            InterfaceField("sample_id", "str", "Sample identifier used to name the output GVCF."),
            InterfaceField("gatk_sif", "str", "Optional Apptainer/Singularity image path for GATK4."),
        ),
        outputs=(
            InterfaceField("gvcf", "File", "Per-sample GVCF produced by GATK4 HaplotypeCaller."),
        ),
        tags=("variant_calling", "gatk4", "gvcf"),
        compatibility=RegistryCompatibilityMetadata(
            biological_stage="GATK4 per-sample GVCF generation",
            accepted_planner_types=("ReferenceGenome", "AlignmentSet"),
            produced_planner_types=("VariantCallSet",),
            reusable_as_reference=False,
            execution_defaults={
                "profile": "local",
                "result_manifest": "run_manifest.json",
                "resources": {"cpu": "8", "memory": "32Gi", "execution_class": "local"},
                "slurm_resource_hints": {"cpu": "16", "memory": "64Gi", "walltime": "24:00:00"},
                "runtime_images": {"gatk_sif": "data/images/gatk4.sif"},
                "module_loads": ("python/3.11.9", "apptainer/1.4.1"),
            },
            supported_execution_profiles=("local", "slurm"),
            synthesis_eligible=True,
            composition_constraints=(
                "Requires coordinate-sorted dedup'd BAM + reference; BQSR-recalibrated BAM strongly recommended.",
            ),
            pipeline_family="variant_calling",
            pipeline_stage_order=5,
        ),
    ),
    RegistryEntry(
        name="combine_gvcfs",
        category="task",
        description="Merge per-sample GVCFs into a cohort GVCF via GATK4 CombineGVCFs.",
        inputs=(
            InterfaceField("reference_fasta", "File", "Reference genome FASTA."),
            InterfaceField("gvcfs", "list[File]", "Per-sample GVCFs to combine; each must have been emitted with --emit-ref-confidence GVCF."),
            InterfaceField("cohort_id", "str", "Cohort identifier used to name the output GVCF."),
            InterfaceField("gatk_sif", "str", "Optional Apptainer/Singularity image path for GATK4."),
        ),
        outputs=(
            InterfaceField("combined_gvcf", "File", "Cohort GVCF produced by GATK4 CombineGVCFs."),
        ),
        tags=("variant_calling", "gatk4", "gvcf", "joint-calling"),
        compatibility=RegistryCompatibilityMetadata(
            biological_stage="GATK4 cohort GVCF merging",
            accepted_planner_types=("ReferenceGenome", "VariantCallSet"),
            produced_planner_types=("VariantCallSet",),
            reusable_as_reference=False,
            execution_defaults={
                "profile": "local",
                "result_manifest": "run_manifest.json",
                "resources": {"cpu": "4", "memory": "16Gi", "execution_class": "local"},
                "slurm_resource_hints": {"cpu": "8", "memory": "32Gi", "walltime": "06:00:00"},
                "runtime_images": {"gatk_sif": "data/images/gatk4.sif"},
                "module_loads": ("python/3.11.9", "apptainer/1.4.1"),
            },
            supported_execution_profiles=("local", "slurm"),
            synthesis_eligible=True,
            composition_constraints=(
                "All input GVCFs must call against the same reference build.",
                "Each GVCF must have been produced with --emit-ref-confidence GVCF.",
            ),
            pipeline_family="variant_calling",
            pipeline_stage_order=6,
        ),
    ),
    RegistryEntry(
        name="joint_call_gvcfs",
        category="task",
        description="Run GenomicsDBImport then GenotypeGVCFs to produce a joint-called VCF for a cohort.",
        inputs=(
            InterfaceField("reference_fasta", "File", "Reference genome FASTA."),
            InterfaceField("gvcfs", "list[File]", "Per-sample GVCFs; each must pair 1:1 with sample_ids."),
            InterfaceField("sample_ids", "list[str]", "Sample identifiers matching the gvcfs list order; written into the GenomicsDB sample-name map."),
            InterfaceField("intervals", "list[str]", "Genomic intervals (e.g. 'chr20') passed to GenomicsDBImport via -L; at least one required."),
            InterfaceField("cohort_id", "str", "Cohort identifier used to name the output VCF."),
            InterfaceField("gatk_sif", "str", "Optional Apptainer/Singularity image path for GATK4."),
        ),
        outputs=(
            InterfaceField("joint_vcf", "File", "Joint-called VCF produced by GATK4 GenotypeGVCFs."),
        ),
        tags=("variant_calling", "gatk4", "joint-calling", "genotyping"),
        compatibility=RegistryCompatibilityMetadata(
            biological_stage="GATK4 joint genotyping",
            accepted_planner_types=("ReferenceGenome", "VariantCallSet"),
            produced_planner_types=("VariantCallSet",),
            reusable_as_reference=False,
            execution_defaults={
                "profile": "local",
                "result_manifest": "run_manifest.json",
                "resources": {"cpu": "8", "memory": "32Gi", "execution_class": "local"},
                "slurm_resource_hints": {"cpu": "16", "memory": "64Gi", "walltime": "24:00:00"},
                "runtime_images": {"gatk_sif": "data/images/gatk4.sif"},
                "module_loads": ("python/3.11.9", "apptainer/1.4.1"),
            },
            supported_execution_profiles=("local", "slurm"),
            synthesis_eligible=True,
            composition_constraints=(
                "Requires a list of GVCFs with matching sample_ids 1:1.",
                "Requires at least one genomic interval.",
            ),
            pipeline_family="variant_calling",
            pipeline_stage_order=7,
        ),
    ),
    RegistryEntry(
        name="bwa_mem2_index",
        category="task",
        description="Index a reference FASTA for BWA-MEM2 alignment.",
        inputs=(
            InterfaceField("ref_path", "str", "Absolute path to reference FASTA."),
            InterfaceField("results_dir", "str", "Directory for index output."),
            InterfaceField("sif_path", "str", "Optional Apptainer/Singularity image path."),
        ),
        outputs=(
            InterfaceField("bwa_index_prefix", "str", "Path prefix for BWA-MEM2 index files."),
        ),
        tags=("variant_calling", "gatk4", "alignment", "reference_prep"),
        compatibility=RegistryCompatibilityMetadata(
            biological_stage="BWA-MEM2 reference indexing",
            accepted_planner_types=("ReferenceGenome",),
            produced_planner_types=("ReferenceGenome",),
            reusable_as_reference=True,
            execution_defaults={
                "profile": "local",
                "result_manifest": "run_manifest.json",
                "resources": {"cpu": "4", "memory": "16Gi", "execution_class": "local"},
                "slurm_resource_hints": {"cpu": "8", "memory": "32Gi", "walltime": "02:00:00"},
                "runtime_images": {"sif_path": "data/images/gatk4.sif"},
                "module_loads": ("python/3.11.9", "apptainer/1.4.1"),
            },
            supported_execution_profiles=("local", "slurm"),
            synthesis_eligible=True,
            composition_constraints=(
                "Requires a reference genome FASTA; output prefix used by bwa_mem2_mem.",
            ),
            pipeline_family="variant_calling",
            pipeline_stage_order=8,
        ),
    ),
    RegistryEntry(
        name="bwa_mem2_mem",
        category="task",
        description="Align paired-end FASTQ reads to a reference using BWA-MEM2.",
        inputs=(
            InterfaceField("ref_path", "str", "Absolute path to reference FASTA."),
            InterfaceField("r1_path", "str", "Absolute path to R1 FASTQ."),
            InterfaceField("sample_id", "str", "Sample identifier."),
            InterfaceField("results_dir", "str", "Output directory."),
            InterfaceField("r2_path", "str", "Optional R2 FASTQ path (empty string for single-end)."),
            InterfaceField("threads", "int", "BWA-MEM2 alignment threads."),
            InterfaceField("sif_path", "str", "Optional Apptainer/Singularity image path."),
        ),
        outputs=(
            InterfaceField("aligned_bam", "str", "Path to unsorted aligned BAM."),
        ),
        tags=("variant_calling", "gatk4", "alignment"),
        compatibility=RegistryCompatibilityMetadata(
            biological_stage="BWA-MEM2 paired-end alignment",
            accepted_planner_types=("ReferenceGenome", "ReadPair"),
            produced_planner_types=("AlignmentSet",),
            reusable_as_reference=False,
            execution_defaults={
                "profile": "local",
                "result_manifest": "run_manifest.json",
                "resources": {"cpu": "8", "memory": "32Gi", "execution_class": "local"},
                "slurm_resource_hints": {"cpu": "16", "memory": "64Gi", "walltime": "08:00:00"},
                "runtime_images": {"sif_path": "data/images/gatk4.sif"},
                "module_loads": ("python/3.11.9", "apptainer/1.4.1"),
            },
            supported_execution_profiles=("local", "slurm"),
            synthesis_eligible=True,
            composition_constraints=(
                "Reference must be indexed by bwa_mem2_index before calling this task.",
            ),
            pipeline_family="variant_calling",
            pipeline_stage_order=9,
        ),
    ),
    RegistryEntry(
        name="sort_sam",
        category="task",
        description="Coordinate-sort a BAM file using GATK SortSam.",
        inputs=(
            InterfaceField("bam_path", "str", "Absolute path to input BAM."),
            InterfaceField("sample_id", "str", "Sample identifier."),
            InterfaceField("results_dir", "str", "Output directory."),
            InterfaceField("sif_path", "str", "Optional Apptainer/Singularity image path."),
        ),
        outputs=(
            InterfaceField("sorted_bam", "str", "Path to coordinate-sorted BAM."),
        ),
        tags=("variant_calling", "gatk4", "preprocessing"),
        compatibility=RegistryCompatibilityMetadata(
            biological_stage="GATK4 coordinate sort",
            accepted_planner_types=("AlignmentSet",),
            produced_planner_types=("AlignmentSet",),
            reusable_as_reference=False,
            execution_defaults={
                "profile": "local",
                "result_manifest": "run_manifest.json",
                "resources": {"cpu": "4", "memory": "16Gi", "execution_class": "local"},
                "slurm_resource_hints": {"cpu": "8", "memory": "32Gi", "walltime": "04:00:00"},
                "runtime_images": {"sif_path": "data/images/gatk4.sif"},
                "module_loads": ("python/3.11.9", "apptainer/1.4.1"),
            },
            supported_execution_profiles=("local", "slurm"),
            synthesis_eligible=True,
            composition_constraints=(
                "Consumes the unsorted BAM from bwa_mem2_mem; emits a coordinate-sorted BAM with index.",
            ),
            pipeline_family="variant_calling",
            pipeline_stage_order=10,
        ),
    ),
    RegistryEntry(
        name="mark_duplicates",
        category="task",
        description="Mark PCR and optical duplicate reads using GATK MarkDuplicates.",
        inputs=(
            InterfaceField("bam_path", "str", "Absolute path to coordinate-sorted BAM."),
            InterfaceField("sample_id", "str", "Sample identifier."),
            InterfaceField("results_dir", "str", "Output directory."),
            InterfaceField("sif_path", "str", "Optional Apptainer/Singularity image path."),
        ),
        outputs=(
            InterfaceField("dedup_bam", "str", "Path to duplicate-marked BAM."),
            InterfaceField("duplicate_metrics", "str", "Path to duplicate metrics file."),
        ),
        tags=("variant_calling", "gatk4", "preprocessing"),
        compatibility=RegistryCompatibilityMetadata(
            biological_stage="GATK4 duplicate marking",
            accepted_planner_types=("AlignmentSet",),
            produced_planner_types=("AlignmentSet",),
            reusable_as_reference=False,
            execution_defaults={
                "profile": "local",
                "result_manifest": "run_manifest.json",
                "resources": {"cpu": "4", "memory": "16Gi", "execution_class": "local"},
                "slurm_resource_hints": {"cpu": "8", "memory": "32Gi", "walltime": "04:00:00"},
                "runtime_images": {"sif_path": "data/images/gatk4.sif"},
                "module_loads": ("python/3.11.9", "apptainer/1.4.1"),
            },
            supported_execution_profiles=("local", "slurm"),
            synthesis_eligible=True,
            composition_constraints=(
                "Input BAM must be coordinate-sorted (sort_sam must have run first).",
            ),
            pipeline_family="variant_calling",
            pipeline_stage_order=11,
        ),
    ),
    RegistryEntry(
        name="prepare_reference",
        category="workflow",
        description="Prepare a reference genome for GATK germline variant calling (dict + known-sites index + BWA-MEM2 index).",
        inputs=(
            InterfaceField("ref_path", "str", "Absolute path to reference FASTA."),
            InterfaceField("known_sites", "list[str]", "List of known-sites VCF paths."),
            InterfaceField("results_dir", "str", "Output directory."),
            InterfaceField("sif_path", "str", "Optional Apptainer/Singularity image path."),
        ),
        outputs=(
            InterfaceField("prepared_ref", "str", "Reference path (with all indices in results_dir)."),
        ),
        tags=("variant_calling", "gatk4", "reference_prep", "workflow"),
        compatibility=RegistryCompatibilityMetadata(
            biological_stage="GATK4 reference preparation",
            accepted_planner_types=("ReferenceGenome", "KnownSites"),
            produced_planner_types=("ReferenceGenome",),
            reusable_as_reference=True,
            execution_defaults={
                "profile": "local",
                "result_manifest": "run_manifest.json",
                "resources": {"cpu": "4", "memory": "16Gi", "execution_class": "local"},
                "slurm_resource_hints": {"cpu": "8", "memory": "32Gi", "walltime": "04:00:00"},
                "runtime_images": {"sif_path": "data/images/gatk4.sif"},
                "module_loads": ("python/3.11.9", "apptainer/1.4.1"),
            },
            supported_execution_profiles=("local", "slurm"),
            synthesis_eligible=True,
            composition_constraints=(
                "Composes create_sequence_dictionary, index_feature_file (per VCF), and bwa_mem2_index.",
            ),
            pipeline_family="variant_calling",
            pipeline_stage_order=1,
        ),
    ),
    RegistryEntry(
        name="preprocess_sample",
        category="workflow",
        description="Preprocess one sample from paired-end FASTQs to BQSR-recalibrated BAM.",
        inputs=(
            InterfaceField("ref_path", "str", "Absolute path to reference FASTA."),
            InterfaceField("r1_path", "str", "Absolute path to R1 FASTQ."),
            InterfaceField("sample_id", "str", "Sample identifier."),
            InterfaceField("known_sites", "list[str]", "List of indexed known-sites VCF paths."),
            InterfaceField("results_dir", "str", "Output directory."),
            InterfaceField("r2_path", "str", "Optional R2 FASTQ path."),
            InterfaceField("threads", "int", "BWA-MEM2 alignment threads."),
            InterfaceField("sif_path", "str", "Optional Apptainer/Singularity image path."),
        ),
        outputs=(
            InterfaceField("preprocessed_bam", "str", "Path to BQSR-recalibrated BAM."),
        ),
        tags=("variant_calling", "gatk4", "preprocessing", "workflow"),
        compatibility=RegistryCompatibilityMetadata(
            biological_stage="GATK4 sample preprocessing",
            accepted_planner_types=("ReferenceGenome", "ReadPair", "KnownSites"),
            produced_planner_types=("AlignmentSet",),
            reusable_as_reference=True,
            execution_defaults={
                "profile": "local",
                "result_manifest": "run_manifest.json",
                "resources": {"cpu": "8", "memory": "32Gi", "execution_class": "local"},
                "slurm_resource_hints": {"cpu": "16", "memory": "64Gi", "walltime": "12:00:00"},
                "runtime_images": {"sif_path": "data/images/gatk4.sif"},
                "module_loads": ("python/3.11.9", "apptainer/1.4.1"),
            },
            supported_execution_profiles=("local", "slurm"),
            synthesis_eligible=True,
            composition_constraints=(
                "Reference must be prepared (prepare_reference must have run first).",
            ),
            pipeline_family="variant_calling",
            pipeline_stage_order=2,
        ),
    ),
    RegistryEntry(
        name="germline_short_variant_discovery",
        category="workflow",
        description="End-to-end germline SNP and indel discovery from raw reads to joint-genotyped VCF.",
        inputs=(
            InterfaceField("ref_path", "str", "Absolute path to reference FASTA."),
            InterfaceField("sample_ids", "list[str]", "Sample identifiers."),
            InterfaceField("r1_paths", "list[str]", "R1 FASTQ paths, 1:1 with sample_ids."),
            InterfaceField("known_sites", "list[str]", "Indexed known-sites VCF paths."),
            InterfaceField("intervals", "list[str]", "Genomic intervals for GenomicsDBImport."),
            InterfaceField("results_dir", "str", "Output directory."),
            InterfaceField("r2_paths", "list[str]", "Optional R2 FASTQ paths (None for single-end)."),
            InterfaceField("cohort_id", "str", "Cohort identifier."),
            InterfaceField("threads", "int", "BWA-MEM2 alignment threads."),
            InterfaceField("sif_path", "str", "Optional Apptainer/Singularity image path."),
        ),
        outputs=(
            InterfaceField("genotyped_vcf", "str", "Path to joint-genotyped VCF."),
        ),
        tags=("variant_calling", "gatk4", "joint-calling", "workflow"),
        compatibility=RegistryCompatibilityMetadata(
            biological_stage="GATK4 germline short variant discovery",
            accepted_planner_types=("ReferenceGenome", "ReadPair", "KnownSites"),
            produced_planner_types=("VariantCallSet",),
            reusable_as_reference=True,
            execution_defaults={
                "profile": "local",
                "result_manifest": "run_manifest.json",
                "resources": {"cpu": "8", "memory": "32Gi", "execution_class": "local"},
                "slurm_resource_hints": {"cpu": "16", "memory": "64Gi", "walltime": "48:00:00"},
                "runtime_images": {"sif_path": "data/images/gatk4.sif"},
                "module_loads": ("python/3.11.9", "apptainer/1.4.1"),
            },
            supported_execution_profiles=("local", "slurm"),
            synthesis_eligible=True,
            composition_constraints=(
                "Reference must be prepared (prepare_reference must have run first).",
                "Per-sample loop is synchronous; no asyncio.gather.",
                "At least one genomic interval is required for GenomicsDBImport.",
            ),
            pipeline_family="variant_calling",
            pipeline_stage_order=3,
        ),
    ),
    RegistryEntry(
        name="genotype_refinement",
        category="workflow",
        description="Refine a joint-called VCF with two-pass VQSR (SNP then INDEL) using GATK4.",
        inputs=(
            InterfaceField("ref_path", "str", "Absolute path to reference FASTA."),
            InterfaceField("joint_vcf", "str", "Absolute path to joint-called cohort VCF."),
            InterfaceField("snp_resources", "list[str]", "VCF paths for SNP VQSR training."),
            InterfaceField("snp_resource_flags", "list[dict]", "Parallel per-resource flag dicts for SNP pass."),
            InterfaceField("indel_resources", "list[str]", "VCF paths for INDEL VQSR training."),
            InterfaceField("indel_resource_flags", "list[dict]", "Parallel per-resource flag dicts for INDEL pass."),
            InterfaceField("cohort_id", "str", "Cohort identifier used to name output files."),
            InterfaceField("results_dir", "str", "Output directory."),
            InterfaceField("snp_filter_level", "float", "SNP truth-sensitivity filter level (0.0 = default 99.5)."),
            InterfaceField("indel_filter_level", "float", "INDEL truth-sensitivity filter level (0.0 = default 99.0)."),
            InterfaceField("sif_path", "str", "Optional Apptainer/Singularity image path."),
        ),
        outputs=(
            InterfaceField("refined_vcf", "str", "Path to the VQSR-refined VCF after both passes."),
        ),
        tags=("variant_calling", "gatk4", "vqsr", "workflow"),
        compatibility=RegistryCompatibilityMetadata(
            biological_stage="GATK4 two-pass VQSR genotype refinement",
            accepted_planner_types=("ReferenceGenome", "VariantCallSet", "KnownSites"),
            produced_planner_types=("VariantCallSet",),
            reusable_as_reference=True,
            execution_defaults={
                "profile": "local",
                "result_manifest": "run_manifest.json",
                "resources": {"cpu": "8", "memory": "32Gi", "execution_class": "local"},
                "slurm_resource_hints": {"cpu": "8", "memory": "32Gi", "walltime": "08:00:00"},
                "runtime_images": {"sif_path": "data/images/gatk4.sif"},
                "module_loads": ("python/3.11.9", "apptainer/1.4.1"),
            },
            supported_execution_profiles=("local", "slurm"),
            synthesis_eligible=True,
            composition_constraints=(
                "Requires a joint-called VCF with sufficient variant count for VQSR training "
                "(chr20 slice is too small; use full chr20 WGS at ≥30x).",
                "INDEL pass consumes the SNP-filtered VCF; pass ordering is mandatory.",
            ),
            pipeline_family="variant_calling",
            pipeline_stage_order=4,
        ),
    ),
    RegistryEntry(
        name="variant_recalibrator",
        category="task",
        description="Build a VQSR recalibration model using GATK4 VariantRecalibrator.",
        inputs=(
            InterfaceField("ref_path", "str", "Absolute path to reference FASTA."),
            InterfaceField("vcf_path", "str", "Absolute path to joint-called cohort VCF."),
            InterfaceField("known_sites", "list[str]", "Parallel list of training/truth VCF paths."),
            InterfaceField("known_sites_flags", "list[dict]", "Parallel list of per-resource flag dicts (resource_name, known, training, truth, prior)."),
            InterfaceField("mode", "str", "Variant type to recalibrate: 'SNP' or 'INDEL'."),
            InterfaceField("cohort_id", "str", "Cohort identifier used to name output files."),
            InterfaceField("results_dir", "str", "Output directory."),
            InterfaceField("sif_path", "str", "Optional Apptainer/Singularity image path."),
        ),
        outputs=(
            InterfaceField("recal_file", "str", "Path to the VQSR recalibration file (.recal)."),
            InterfaceField("tranches_file", "str", "Path to the VQSR tranches file (.tranches)."),
        ),
        tags=("variant_calling", "gatk4", "vqsr"),
        compatibility=RegistryCompatibilityMetadata(
            biological_stage="GATK4 VQSR recalibration model building",
            accepted_planner_types=("ReferenceGenome", "VariantCallSet", "KnownSites"),
            produced_planner_types=(),
            reusable_as_reference=False,
            execution_defaults={
                "profile": "local",
                "result_manifest": "run_manifest.json",
                "resources": {"cpu": "4", "memory": "16Gi", "execution_class": "local"},
                "slurm_resource_hints": {"cpu": "4", "memory": "16Gi", "walltime": "04:00:00"},
                "runtime_images": {"sif_path": "data/images/gatk4.sif"},
                "module_loads": ("python/3.11.9", "apptainer/1.4.1"),
            },
            supported_execution_profiles=("local", "slurm"),
            synthesis_eligible=True,
            composition_constraints=(
                "Requires a joint-called cohort VCF with sufficient variant count "
                "(≥30k SNPs for SNP mode; ≥2k indels for INDEL mode). "
                "The chr20 NA12878 slice in variant_calling_germline_minimal is too small; "
                "use the full-chr20 WGS data from variant_calling_vqsr_chr20 bundle.",
                "All known-sites VCFs must be indexed (.tbi or .idx present next to each VCF).",
            ),
            pipeline_family="variant_calling",
            pipeline_stage_order=12,
        ),
    ),
    RegistryEntry(
        name="apply_vqsr",
        category="task",
        description="Apply a VQSR recalibration model to a VCF using GATK4 ApplyVQSR.",
        inputs=(
            InterfaceField("ref_path", "str", "Absolute path to reference FASTA."),
            InterfaceField("vcf_path", "str", "Absolute path to input VCF (joint-called or SNP-filtered)."),
            InterfaceField("recal_file", "str", "Recalibration file from variant_recalibrator."),
            InterfaceField("tranches_file", "str", "Tranches file from variant_recalibrator."),
            InterfaceField("mode", "str", "Variant type to apply: 'SNP' or 'INDEL'."),
            InterfaceField("cohort_id", "str", "Cohort identifier used to name output files."),
            InterfaceField("results_dir", "str", "Output directory."),
            InterfaceField("truth_sensitivity_filter_level", "float", "VQSLOD filter threshold (0.0 = use default: 99.5 SNP / 99.0 INDEL)."),
            InterfaceField("sif_path", "str", "Optional Apptainer/Singularity image path."),
        ),
        outputs=(
            InterfaceField("vqsr_vcf", "str", "Path to the VQSR-filtered VCF (.vcf.gz)."),
        ),
        tags=("variant_calling", "gatk4", "vqsr"),
        compatibility=RegistryCompatibilityMetadata(
            biological_stage="GATK4 VQSR filter application",
            accepted_planner_types=("ReferenceGenome", "VariantCallSet"),
            produced_planner_types=("VariantCallSet",),
            reusable_as_reference=False,
            execution_defaults={
                "profile": "local",
                "result_manifest": "run_manifest.json",
                "resources": {"cpu": "4", "memory": "16Gi", "execution_class": "local"},
                "slurm_resource_hints": {"cpu": "4", "memory": "16Gi", "walltime": "02:00:00"},
                "runtime_images": {"sif_path": "data/images/gatk4.sif"},
                "module_loads": ("python/3.11.9", "apptainer/1.4.1"),
            },
            supported_execution_profiles=("local", "slurm"),
            synthesis_eligible=True,
            composition_constraints=(
                "recal_file and tranches_file must come from variant_recalibrator for the same mode.",
                "INDEL pass must consume the SNP-filtered VCF from a prior apply_vqsr SNP call, "
                "not the original joint VCF.",
            ),
            pipeline_family="variant_calling",
            pipeline_stage_order=13,
        ),
    ),
    RegistryEntry(
        name="merge_bam_alignment",
        category="task",
        description="Merge aligned BAM with unmapped BAM using GATK4 MergeBamAlignment.",
        inputs=(
            InterfaceField("ref_path", "str", "Absolute path to reference FASTA."),
            InterfaceField("aligned_bam", "str", "Absolute path to aligned (unsorted) BAM from bwa_mem2_mem."),
            InterfaceField("ubam_path", "str", "Absolute path to queryname-sorted unmapped BAM."),
            InterfaceField("sample_id", "str", "Sample identifier used to name the output BAM."),
            InterfaceField("results_dir", "str", "Output directory."),
            InterfaceField("sif_path", "str", "Optional Apptainer/Singularity image path."),
        ),
        outputs=(
            InterfaceField("merged_bam", "str", "Path to the coordinate-sorted merged BAM."),
        ),
        tags=("variant_calling", "gatk4", "preprocessing"),
        compatibility=RegistryCompatibilityMetadata(
            biological_stage="GATK4 BAM alignment merging (uBAM path)",
            accepted_planner_types=("ReferenceGenome", "AlignmentSet", "UnmappedBAM"),
            produced_planner_types=("AlignmentSet",),
            reusable_as_reference=False,
            execution_defaults={
                "profile": "local",
                "result_manifest": "run_manifest.json",
                "resources": {"cpu": "4", "memory": "16Gi", "execution_class": "local"},
                "slurm_resource_hints": {"cpu": "4", "memory": "16Gi", "walltime": "02:00:00"},
                "runtime_images": {"sif_path": "data/images/gatk4.sif"},
                "module_loads": ("python/3.11.9", "apptainer/1.4.1"),
            },
            supported_execution_profiles=("local", "slurm"),
            synthesis_eligible=True,
            composition_constraints=(
                "ubam_path must be queryname-sorted (GATK MergeBamAlignment requirement).",
                "Output is coordinate-sorted; no sort_sam step needed after this task.",
            ),
            pipeline_family="variant_calling",
            pipeline_stage_order=14,
        ),
    ),
)
