"""Registry entries for the variant_calling pipeline family."""

from __future__ import annotations

from flytetest.registry._types import (
    InterfaceField,
    RegistryCompatibilityMetadata,
    RegistryEntry,
)

VARIANT_CALLING_ENTRIES: tuple[RegistryEntry, ...] = (
    RegistryEntry(
        name="create_sequence_dictionary",
        category="task",
        description="Emit a GATK4 sequence dictionary (.dict) next to a reference FASTA via CreateSequenceDictionary.",
        inputs=(
            InterfaceField("reference_fasta", "File", "Reference genome FASTA."),
            InterfaceField("gatk_sif", "str", "Optional Apptainer/Singularity image path for GATK4."),
        ),
        outputs=(
            InterfaceField("sequence_dict", "File", "GATK4 sequence dictionary (.dict) file emitted next to the reference FASTA."),
        ),
        tags=("variant_calling", "gatk4", "reference_prep"),
        compatibility=RegistryCompatibilityMetadata(
            biological_stage="GATK4 reference sequence dictionary",
            accepted_planner_types=("ReferenceGenome",),
            produced_planner_types=(),
            reusable_as_reference=True,
            execution_defaults={
                "profile": "local",
                "result_manifest": "run_manifest.json",
                "resources": {"cpu": "1", "memory": "4Gi", "execution_class": "local"},
                "slurm_resource_hints": {"cpu": "1", "memory": "4Gi", "walltime": "00:30:00"},
                "runtime_images": {"gatk_sif": "data/images/gatk4.sif"},
                "module_loads": ("python/3.11.9", "apptainer/1.4.1"),
            },
            supported_execution_profiles=("local", "slurm"),
            synthesis_eligible=True,
            composition_constraints=(
                "Requires a reference genome FASTA; emits the sequence dictionary downstream tools depend on.",
            ),
            pipeline_family="variant_calling",
            pipeline_stage_order=1,
        ),
        showcase_module="flytetest.tasks.variant_calling",
    ),
    RegistryEntry(
        name="index_feature_file",
        category="task",
        description="Emit a GATK4 feature-file index (.idx or .tbi) next to a VCF/GVCF via IndexFeatureFile.",
        inputs=(
            InterfaceField("vcf", "File", "VCF or GVCF to index."),
            InterfaceField("gatk_sif", "str", "Optional Apptainer/Singularity image path for GATK4."),
        ),
        outputs=(
            InterfaceField("feature_index", "File", "GATK4 index (.idx for plain VCF, .tbi for .vcf.gz) written next to the input VCF."),
        ),
        tags=("variant_calling", "gatk4", "reference_prep"),
        compatibility=RegistryCompatibilityMetadata(
            biological_stage="GATK4 feature-file indexing",
            accepted_planner_types=("KnownSites",),
            produced_planner_types=(),
            reusable_as_reference=True,
            execution_defaults={
                "profile": "local",
                "result_manifest": "run_manifest.json",
                "resources": {"cpu": "1", "memory": "4Gi", "execution_class": "local"},
                "slurm_resource_hints": {"cpu": "1", "memory": "4Gi", "walltime": "00:30:00"},
                "runtime_images": {"gatk_sif": "data/images/gatk4.sif"},
                "module_loads": ("python/3.11.9", "apptainer/1.4.1"),
            },
            supported_execution_profiles=("local", "slurm"),
            synthesis_eligible=True,
            composition_constraints=(
                "Requires a VCF or GVCF; emits the index file BQSR and downstream steps depend on.",
            ),
            pipeline_family="variant_calling",
            pipeline_stage_order=2,
        ),
        showcase_module="flytetest.tasks.variant_calling",
    ),
    RegistryEntry(
        name="base_recalibrator",
        category="task",
        description="Generate a GATK4 BQSR recalibration table via BaseRecalibrator.",
        inputs=(
            InterfaceField("reference_fasta", "File", "Reference genome FASTA."),
            InterfaceField("aligned_bam", "File", "Coordinate-sorted, duplicate-marked BAM."),
            InterfaceField("known_sites", "list[File]", "Indexed known-sites VCF(s) for BQSR."),
            InterfaceField("sample_id", "str", "Sample identifier used to name the output table."),
            InterfaceField("gatk_sif", "str", "Optional Apptainer/Singularity image path for GATK4."),
        ),
        outputs=(
            InterfaceField("bqsr_report", "File", "GATK4 BQSR recalibration table (.table)."),
        ),
        tags=("variant_calling", "gatk4", "bqsr"),
        compatibility=RegistryCompatibilityMetadata(
            biological_stage="GATK4 base quality score recalibration report",
            accepted_planner_types=("ReferenceGenome", "AlignmentSet", "KnownSites"),
            produced_planner_types=(),
            reusable_as_reference=False,
            execution_defaults={
                "profile": "local",
                "result_manifest": "run_manifest.json",
                "resources": {"cpu": "4", "memory": "16Gi", "execution_class": "local"},
                "slurm_resource_hints": {"cpu": "8", "memory": "32Gi", "walltime": "06:00:00"},
                "runtime_images": {"gatk_sif": "data/images/gatk4.sif"},
                "module_loads": ("python/3.11.9", "apptainer/1.4.1"),
            },
            supported_execution_profiles=("local", "slurm"),
            synthesis_eligible=True,
            composition_constraints=(
                "Requires coordinate-sorted dedup'd BAM + reference + ≥1 indexed known-sites VCF.",
            ),
            pipeline_family="variant_calling",
            pipeline_stage_order=3,
        ),
        showcase_module="flytetest.tasks.variant_calling",
    ),
    RegistryEntry(
        name="apply_bqsr",
        category="task",
        description="Apply a GATK4 BQSR recalibration table to an aligned BAM via ApplyBQSR.",
        inputs=(
            InterfaceField("reference_fasta", "File", "Reference genome FASTA."),
            InterfaceField("aligned_bam", "File", "Coordinate-sorted, duplicate-marked BAM."),
            InterfaceField("bqsr_report", "File", "BQSR recalibration table from base_recalibrator."),
            InterfaceField("sample_id", "str", "Sample identifier used to name the output BAM."),
            InterfaceField("gatk_sif", "str", "Optional Apptainer/Singularity image path for GATK4."),
        ),
        outputs=(
            InterfaceField("recalibrated_bam", "File", "Recalibrated BAM produced by GATK4 ApplyBQSR."),
        ),
        tags=("variant_calling", "gatk4", "bqsr"),
        compatibility=RegistryCompatibilityMetadata(
            biological_stage="GATK4 apply base quality score recalibration",
            accepted_planner_types=("ReferenceGenome", "AlignmentSet"),
            produced_planner_types=("AlignmentSet",),
            reusable_as_reference=False,
            execution_defaults={
                "profile": "local",
                "result_manifest": "run_manifest.json",
                "resources": {"cpu": "4", "memory": "16Gi", "execution_class": "local"},
                "slurm_resource_hints": {"cpu": "8", "memory": "32Gi", "walltime": "06:00:00"},
                "runtime_images": {"gatk_sif": "data/images/gatk4.sif"},
                "module_loads": ("python/3.11.9", "apptainer/1.4.1"),
            },
            supported_execution_profiles=("local", "slurm"),
            synthesis_eligible=True,
            composition_constraints=(
                "Requires coordinate-sorted dedup'd BAM + reference + BQSR table from base_recalibrator.",
            ),
            pipeline_family="variant_calling",
            pipeline_stage_order=4,
        ),
        showcase_module="flytetest.tasks.variant_calling",
    ),
    RegistryEntry(
        name="haplotype_caller",
        category="task",
        description="Call per-sample germline variants in GVCF mode via GATK4 HaplotypeCaller.",
        inputs=(
            InterfaceField("reference_fasta", "File", "Reference genome FASTA."),
            InterfaceField("aligned_bam", "File", "Coordinate-sorted, dedup'd, BQSR-recalibrated BAM."),
            InterfaceField("sample_id", "str", "Sample identifier used to name the output GVCF."),
            InterfaceField("gatk_sif", "str", "Optional Apptainer/Singularity image path for GATK4."),
        ),
        outputs=(
            InterfaceField("gvcf", "File", "Per-sample GVCF produced by GATK4 HaplotypeCaller."),
        ),
        tags=("variant_calling", "gatk4", "gvcf"),
        compatibility=RegistryCompatibilityMetadata(
            biological_stage="GATK4 per-sample GVCF generation",
            accepted_planner_types=("ReferenceGenome", "AlignmentSet"),
            produced_planner_types=("VariantCallSet",),
            reusable_as_reference=False,
            execution_defaults={
                "profile": "local",
                "result_manifest": "run_manifest.json",
                "resources": {"cpu": "8", "memory": "32Gi", "execution_class": "local"},
                "slurm_resource_hints": {"cpu": "16", "memory": "64Gi", "walltime": "24:00:00"},
                "runtime_images": {"gatk_sif": "data/images/gatk4.sif"},
                "module_loads": ("python/3.11.9", "apptainer/1.4.1"),
            },
            supported_execution_profiles=("local", "slurm"),
            synthesis_eligible=True,
            composition_constraints=(
                "Requires coordinate-sorted dedup'd BAM + reference; BQSR-recalibrated BAM strongly recommended.",
            ),
            pipeline_family="variant_calling",
            pipeline_stage_order=5,
        ),
        showcase_module="flytetest.tasks.variant_calling",
    ),
    RegistryEntry(
        name="combine_gvcfs",
        category="task",
        description="Merge per-sample GVCFs into a cohort GVCF via GATK4 CombineGVCFs.",
        inputs=(
            InterfaceField("reference_fasta", "File", "Reference genome FASTA."),
            InterfaceField("gvcfs", "list[File]", "Per-sample GVCFs to combine; each must have been emitted with --emit-ref-confidence GVCF."),
            InterfaceField("cohort_id", "str", "Cohort identifier used to name the output GVCF."),
            InterfaceField("gatk_sif", "str", "Optional Apptainer/Singularity image path for GATK4."),
        ),
        outputs=(
            InterfaceField("combined_gvcf", "File", "Cohort GVCF produced by GATK4 CombineGVCFs."),
        ),
        tags=("variant_calling", "gatk4", "gvcf", "joint-calling"),
        compatibility=RegistryCompatibilityMetadata(
            biological_stage="GATK4 cohort GVCF merging",
            accepted_planner_types=("ReferenceGenome", "VariantCallSet"),
            produced_planner_types=("VariantCallSet",),
            reusable_as_reference=False,
            execution_defaults={
                "profile": "local",
                "result_manifest": "run_manifest.json",
                "resources": {"cpu": "4", "memory": "16Gi", "execution_class": "local"},
                "slurm_resource_hints": {"cpu": "8", "memory": "32Gi", "walltime": "06:00:00"},
                "runtime_images": {"gatk_sif": "data/images/gatk4.sif"},
                "module_loads": ("python/3.11.9", "apptainer/1.4.1"),
            },
            supported_execution_profiles=("local", "slurm"),
            synthesis_eligible=True,
            composition_constraints=(
                "All input GVCFs must call against the same reference build.",
                "Each GVCF must have been produced with --emit-ref-confidence GVCF.",
            ),
            pipeline_family="variant_calling",
            pipeline_stage_order=6,
        ),
        showcase_module="flytetest.tasks.variant_calling",
    ),
    RegistryEntry(
        name="joint_call_gvcfs",
        category="task",
        description="Run GenomicsDBImport then GenotypeGVCFs to produce a joint-called VCF for a cohort.",
        inputs=(
            InterfaceField("reference_fasta", "File", "Reference genome FASTA."),
            InterfaceField("gvcfs", "list[File]", "Per-sample GVCFs; each must pair 1:1 with sample_ids."),
            InterfaceField("sample_ids", "list[str]", "Sample identifiers matching the gvcfs list order."),
            InterfaceField("intervals", "list[str]", "Genomic intervals (e.g. 'chr20') passed to GenomicsDBImport via -L; at least one required."),
            InterfaceField("cohort_id", "str", "Cohort identifier used to name the output VCF."),
            InterfaceField("gatk_sif", "str", "Optional Apptainer/Singularity image path for GATK4."),
        ),
        outputs=(
            InterfaceField("joint_vcf", "File", "Joint-called VCF produced by GATK4 GenotypeGVCFs."),
        ),
        tags=("variant_calling", "gatk4", "joint-calling", "genotyping"),
        compatibility=RegistryCompatibilityMetadata(
            biological_stage="GATK4 joint genotyping",
            accepted_planner_types=("ReferenceGenome", "VariantCallSet"),
            produced_planner_types=("VariantCallSet",),
            reusable_as_reference=False,
            execution_defaults={
                "profile": "local",
                "result_manifest": "run_manifest.json",
                "resources": {"cpu": "8", "memory": "32Gi", "execution_class": "local"},
                "slurm_resource_hints": {"cpu": "16", "memory": "64Gi", "walltime": "24:00:00"},
                "runtime_images": {"gatk_sif": "data/images/gatk4.sif"},
                "module_loads": ("python/3.11.9", "apptainer/1.4.1"),
            },
            supported_execution_profiles=("local", "slurm"),
            synthesis_eligible=True,
            composition_constraints=(
                "Requires a list of GVCFs with matching sample_ids 1:1.",
                "Requires at least one genomic interval.",
            ),
            pipeline_family="variant_calling",
            pipeline_stage_order=7,
        ),
        showcase_module="flytetest.tasks.variant_calling",
    ),
    # ---------------------------------------------------------------------------
    # Ported task entries (Milestone I Steps 01–02)
    # ---------------------------------------------------------------------------
    RegistryEntry(
        name="bwa_mem2_index",
        category="task",
        description="Index a reference FASTA for BWA-MEM2 alignment.",
        inputs=(
            InterfaceField("reference_fasta", "File", "Reference genome FASTA."),
            InterfaceField("gatk_sif", "str", "Optional Apptainer/Singularity image path."),
        ),
        outputs=(
            InterfaceField("bwa_index_prefix", "Dir", "Directory containing BWA-MEM2 index files."),
        ),
        tags=("variant_calling", "gatk4", "alignment", "reference_prep"),
        compatibility=RegistryCompatibilityMetadata(
            biological_stage="BWA-MEM2 reference indexing",
            accepted_planner_types=("ReferenceGenome",),
            produced_planner_types=("ReferenceGenome",),
            reusable_as_reference=True,
            execution_defaults={
                "profile": "local",
                "result_manifest": "run_manifest.json",
                "resources": {"cpu": "4", "memory": "16Gi", "execution_class": "local"},
                "slurm_resource_hints": {"cpu": "8", "memory": "32Gi", "walltime": "02:00:00"},
                "runtime_images": {"gatk_sif": "data/images/gatk4.sif"},
                "module_loads": ("python/3.11.9", "apptainer/1.4.1"),
            },
            supported_execution_profiles=("local", "slurm"),
            synthesis_eligible=True,
            composition_constraints=(
                "Requires a reference genome FASTA; output Dir used by bwa_mem2_mem.",
            ),
            pipeline_family="variant_calling",
            pipeline_stage_order=8,
        ),
        showcase_module="flytetest.tasks.variant_calling",
    ),
    RegistryEntry(
        name="bwa_mem2_mem",
        category="task",
        description="Align paired-end FASTQ reads to a reference using BWA-MEM2.",
        inputs=(
            InterfaceField("reference_fasta", "File", "Reference genome FASTA."),
            InterfaceField("r1", "File", "R1 FASTQ file."),
            InterfaceField("sample_id", "str", "Sample identifier."),
            InterfaceField("r2", "File", "Optional R2 FASTQ file (None for single-end)."),
            InterfaceField("threads", "int", "BWA-MEM2 alignment threads."),
            InterfaceField("library_id", "str", "Optional library ID for read-group (default: <sample_id>_lib)."),
            InterfaceField("platform", "str", "Sequencing platform for read-group (default: ILLUMINA)."),
            InterfaceField("gatk_sif", "str", "Optional Apptainer/Singularity image path."),
        ),
        outputs=(
            InterfaceField("aligned_bam", "File", "Unsorted aligned BAM."),
        ),
        tags=("variant_calling", "gatk4", "alignment"),
        compatibility=RegistryCompatibilityMetadata(
            biological_stage="BWA-MEM2 paired-end alignment",
            accepted_planner_types=("ReferenceGenome", "ReadPair"),
            produced_planner_types=("AlignmentSet",),
            reusable_as_reference=False,
            execution_defaults={
                "profile": "local",
                "result_manifest": "run_manifest.json",
                "resources": {"cpu": "8", "memory": "32Gi", "execution_class": "local"},
                "slurm_resource_hints": {"cpu": "16", "memory": "64Gi", "walltime": "08:00:00"},
                "runtime_images": {"gatk_sif": "data/images/gatk4.sif"},
                "module_loads": ("python/3.11.9", "apptainer/1.4.1"),
            },
            supported_execution_profiles=("local", "slurm"),
            synthesis_eligible=True,
            composition_constraints=(
                "Reference must be indexed by bwa_mem2_index before calling this task.",
            ),
            pipeline_family="variant_calling",
            pipeline_stage_order=9,
        ),
        showcase_module="flytetest.tasks.variant_calling",
    ),
    RegistryEntry(
        name="sort_sam",
        category="task",
        description="Coordinate-sort a BAM file using GATK SortSam.",
        inputs=(
            InterfaceField("aligned_bam", "File", "Unsorted aligned BAM."),
            InterfaceField("sample_id", "str", "Sample identifier."),
            InterfaceField("gatk_sif", "str", "Optional Apptainer/Singularity image path."),
        ),
        outputs=(
            InterfaceField("sorted_bam", "File", "Coordinate-sorted BAM."),
        ),
        tags=("variant_calling", "gatk4", "preprocessing"),
        compatibility=RegistryCompatibilityMetadata(
            biological_stage="GATK4 coordinate sort",
            accepted_planner_types=("AlignmentSet",),
            produced_planner_types=("AlignmentSet",),
            reusable_as_reference=False,
            execution_defaults={
                "profile": "local",
                "result_manifest": "run_manifest.json",
                "resources": {"cpu": "4", "memory": "16Gi", "execution_class": "local"},
                "slurm_resource_hints": {"cpu": "8", "memory": "32Gi", "walltime": "04:00:00"},
                "runtime_images": {"gatk_sif": "data/images/gatk4.sif"},
                "module_loads": ("python/3.11.9", "apptainer/1.4.1"),
            },
            supported_execution_profiles=("local", "slurm"),
            synthesis_eligible=True,
            composition_constraints=(
                "Consumes the unsorted BAM from bwa_mem2_mem; emits a coordinate-sorted BAM with index.",
            ),
            pipeline_family="variant_calling",
            pipeline_stage_order=10,
        ),
        showcase_module="flytetest.tasks.variant_calling",
    ),
    RegistryEntry(
        name="mark_duplicates",
        category="task",
        description="Mark PCR and optical duplicate reads using GATK MarkDuplicates.",
        inputs=(
            InterfaceField("sorted_bam", "File", "Coordinate-sorted BAM."),
            InterfaceField("sample_id", "str", "Sample identifier."),
            InterfaceField("gatk_sif", "str", "Optional Apptainer/Singularity image path."),
        ),
        outputs=(
            InterfaceField("dedup_bam", "File", "Duplicate-marked BAM."),
            InterfaceField("duplicate_metrics", "File", "Duplicate metrics file."),
        ),
        tags=("variant_calling", "gatk4", "preprocessing"),
        compatibility=RegistryCompatibilityMetadata(
            biological_stage="GATK4 duplicate marking",
            accepted_planner_types=("AlignmentSet",),
            produced_planner_types=("AlignmentSet",),
            reusable_as_reference=False,
            execution_defaults={
                "profile": "local",
                "result_manifest": "run_manifest.json",
                "resources": {"cpu": "4", "memory": "16Gi", "execution_class": "local"},
                "slurm_resource_hints": {"cpu": "8", "memory": "32Gi", "walltime": "04:00:00"},
                "runtime_images": {"gatk_sif": "data/images/gatk4.sif"},
                "module_loads": ("python/3.11.9", "apptainer/1.4.1"),
            },
            supported_execution_profiles=("local", "slurm"),
            synthesis_eligible=True,
            composition_constraints=(
                "Input BAM must be coordinate-sorted (sort_sam must have run first).",
            ),
            pipeline_family="variant_calling",
            pipeline_stage_order=11,
        ),
        showcase_module="flytetest.tasks.variant_calling",
    ),
    RegistryEntry(
        name="variant_recalibrator",
        category="task",
        description="Build a VQSR recalibration model using GATK4 VariantRecalibrator.",
        inputs=(
            InterfaceField("reference_fasta", "File", "Reference genome FASTA."),
            InterfaceField("cohort_vcf", "File", "Joint-called cohort VCF."),
            InterfaceField("known_sites", "list[File]", "Parallel list of training/truth VCF Files."),
            InterfaceField("known_sites_flags", "list[dict]", "Parallel list of per-resource flag dicts (resource_name, known, training, truth, prior)."),
            InterfaceField("mode", "str", "Variant type to recalibrate: 'SNP' or 'INDEL'."),
            InterfaceField("cohort_id", "str", "Cohort identifier used to name output files."),
            InterfaceField("sample_count", "int", "Number of unrelated samples; triggers auto-InbreedingCoeff at ≥10."),
            InterfaceField("annotations", "list[str]", "Optional override for -an annotation list."),
            InterfaceField("gatk_sif", "str", "Optional Apptainer/Singularity image path."),
        ),
        outputs=(
            InterfaceField("recal_file", "File", "VQSR recalibration file (.recal)."),
            InterfaceField("tranches_file", "File", "VQSR tranches file (.tranches)."),
        ),
        tags=("variant_calling", "gatk4", "vqsr"),
        compatibility=RegistryCompatibilityMetadata(
            biological_stage="GATK4 VQSR recalibration model building",
            accepted_planner_types=("ReferenceGenome", "VariantCallSet", "KnownSites"),
            produced_planner_types=(),
            reusable_as_reference=False,
            execution_defaults={
                "profile": "local",
                "result_manifest": "run_manifest.json",
                "resources": {"cpu": "4", "memory": "16Gi", "execution_class": "local"},
                "slurm_resource_hints": {"cpu": "4", "memory": "16Gi", "walltime": "04:00:00"},
                "runtime_images": {"gatk_sif": "data/images/gatk4.sif"},
                "module_loads": ("python/3.11.9", "apptainer/1.4.1"),
            },
            supported_execution_profiles=("local", "slurm"),
            synthesis_eligible=True,
            composition_constraints=(
                "Requires a joint-called cohort VCF with sufficient variant count "
                "(≥30k SNPs for SNP mode; ≥2k indels for INDEL mode). "
                "The chr20 NA12878 slice in variant_calling_germline_minimal is too small; "
                "use the full-chr20 WGS data from variant_calling_vqsr_chr20 bundle.",
                "All known-sites VCFs must be indexed (.tbi or .idx present next to each VCF).",
                "InbreedingCoeff is auto-added to SNP annotations when sample_count >= 10 (GATK Best Practices).",
            ),
            pipeline_family="variant_calling",
            pipeline_stage_order=12,
        ),
        showcase_module="flytetest.tasks.variant_calling",
    ),
    RegistryEntry(
        name="apply_vqsr",
        category="task",
        description="Apply a VQSR recalibration model to a VCF using GATK4 ApplyVQSR.",
        inputs=(
            InterfaceField("reference_fasta", "File", "Reference genome FASTA."),
            InterfaceField("input_vcf", "File", "Input VCF (joint-called or SNP-filtered)."),
            InterfaceField("recal_file", "File", "Recalibration file from variant_recalibrator."),
            InterfaceField("tranches_file", "File", "Tranches file from variant_recalibrator."),
            InterfaceField("mode", "str", "Variant type to apply: 'SNP' or 'INDEL'."),
            InterfaceField("cohort_id", "str", "Cohort identifier used to name output files."),
            InterfaceField("truth_sensitivity_filter_level", "float", "VQSLOD filter threshold (0.0 = default: 99.5 SNP / 99.0 INDEL)."),
            InterfaceField("gatk_sif", "str", "Optional Apptainer/Singularity image path."),
        ),
        outputs=(
            InterfaceField("vqsr_vcf", "File", "VQSR-filtered VCF (.vcf.gz)."),
        ),
        tags=("variant_calling", "gatk4", "vqsr"),
        compatibility=RegistryCompatibilityMetadata(
            biological_stage="GATK4 VQSR filter application",
            accepted_planner_types=("ReferenceGenome", "VariantCallSet"),
            produced_planner_types=("VariantCallSet",),
            reusable_as_reference=False,
            execution_defaults={
                "profile": "local",
                "result_manifest": "run_manifest.json",
                "resources": {"cpu": "4", "memory": "16Gi", "execution_class": "local"},
                "slurm_resource_hints": {"cpu": "4", "memory": "16Gi", "walltime": "02:00:00"},
                "runtime_images": {"gatk_sif": "data/images/gatk4.sif"},
                "module_loads": ("python/3.11.9", "apptainer/1.4.1"),
            },
            supported_execution_profiles=("local", "slurm"),
            synthesis_eligible=True,
            composition_constraints=(
                "recal_file and tranches_file must come from variant_recalibrator for the same mode.",
                "INDEL pass must consume the SNP-filtered VCF from a prior apply_vqsr SNP call, "
                "not the original joint VCF.",
            ),
            pipeline_family="variant_calling",
            pipeline_stage_order=13,
        ),
        showcase_module="flytetest.tasks.variant_calling",
    ),
    RegistryEntry(
        name="merge_bam_alignment",
        category="task",
        description="Merge aligned BAM with unmapped BAM using GATK4 MergeBamAlignment.",
        inputs=(
            InterfaceField("reference_fasta", "File", "Reference genome FASTA."),
            InterfaceField("aligned_bam", "File", "Aligned (unsorted) BAM from bwa_mem2_mem."),
            InterfaceField("ubam", "File", "Queryname-sorted unmapped BAM."),
            InterfaceField("sample_id", "str", "Sample identifier used to name the output BAM."),
            InterfaceField("gatk_sif", "str", "Optional Apptainer/Singularity image path."),
        ),
        outputs=(
            InterfaceField("merged_bam", "File", "Coordinate-sorted merged BAM."),
        ),
        tags=("variant_calling", "gatk4", "preprocessing"),
        compatibility=RegistryCompatibilityMetadata(
            biological_stage="GATK4 BAM alignment merging (uBAM path)",
            accepted_planner_types=("ReferenceGenome", "AlignmentSet", "UnmappedBAM"),
            produced_planner_types=("AlignmentSet",),
            reusable_as_reference=False,
            execution_defaults={
                "profile": "local",
                "result_manifest": "run_manifest.json",
                "resources": {"cpu": "4", "memory": "16Gi", "execution_class": "local"},
                "slurm_resource_hints": {"cpu": "4", "memory": "16Gi", "walltime": "02:00:00"},
                "runtime_images": {"gatk_sif": "data/images/gatk4.sif"},
                "module_loads": ("python/3.11.9", "apptainer/1.4.1"),
            },
            supported_execution_profiles=("local", "slurm"),
            synthesis_eligible=True,
            composition_constraints=(
                "ubam must be queryname-sorted (GATK MergeBamAlignment requirement).",
                "Output is coordinate-sorted; no sort_sam step needed after this task.",
            ),
            pipeline_family="variant_calling",
            pipeline_stage_order=14,
        ),
        showcase_module="flytetest.tasks.variant_calling",
    ),
    RegistryEntry(
        name="gather_vcfs",
        category="task",
        description="Merge ordered per-interval GVCFs into a single GVCF using GATK GatherVcfs.",
        inputs=(
            InterfaceField("gvcfs", "list[File]", "Ordered list of per-interval GVCF Files (genomic order, non-overlapping)."),
            InterfaceField("sample_id", "str", "Sample identifier used to name the output GVCF."),
            InterfaceField("gatk_sif", "str", "Optional Apptainer/Singularity image path."),
        ),
        outputs=(
            InterfaceField("gathered_gvcf", "File", "Merged GVCF (.g.vcf.gz)."),
        ),
        tags=("variant_calling", "gatk4", "gvcf", "scatter-gather"),
        compatibility=RegistryCompatibilityMetadata(
            biological_stage="GATK4 per-interval GVCF merging",
            accepted_planner_types=("VariantCallSet",),
            produced_planner_types=("VariantCallSet",),
            reusable_as_reference=False,
            execution_defaults={
                "profile": "local",
                "result_manifest": "run_manifest.json",
                "resources": {"cpu": "2", "memory": "8Gi", "execution_class": "local"},
                "slurm_resource_hints": {"cpu": "2", "memory": "8Gi", "walltime": "01:00:00"},
                "runtime_images": {"gatk_sif": "data/images/gatk4.sif"},
                "module_loads": ("python/3.11.9", "apptainer/1.4.1"),
            },
            supported_execution_profiles=("local", "slurm"),
            synthesis_eligible=True,
            composition_constraints=(
                "gvcfs must be in genomic interval order; GatherVcfs requires non-overlapping inputs.",
                "All input GVCFs must be indexed (.tbi or .idx next to each file).",
            ),
            pipeline_family="variant_calling",
            pipeline_stage_order=15,
        ),
        showcase_module="flytetest.tasks.variant_calling",
    ),
    RegistryEntry(
        name="calculate_genotype_posteriors",
        category="task",
        description="Refine genotype posteriors using population priors via GATK4 CalculateGenotypePosteriors.",
        inputs=(
            InterfaceField("input_vcf", "File", "Input VCF (joint-called or VQSR-filtered)."),
            InterfaceField("cohort_id", "str", "Cohort identifier used to name the output VCF."),
            InterfaceField("supporting_callsets", "list[File]", "Optional list of population VCF Files for prior refinement."),
            InterfaceField("gatk_sif", "str", "Optional Apptainer/Singularity image path."),
        ),
        outputs=(
            InterfaceField("cgp_vcf", "File", "CGP-refined VCF (.vcf.gz)."),
        ),
        tags=("variant_calling", "gatk4", "cgp", "genotype-refinement"),
        compatibility=RegistryCompatibilityMetadata(
            biological_stage="GATK4 genotype posterior calculation",
            accepted_planner_types=("VariantCallSet",),
            produced_planner_types=("VariantCallSet",),
            reusable_as_reference=False,
            execution_defaults={
                "profile": "local",
                "result_manifest": "run_manifest.json",
                "resources": {"cpu": "4", "memory": "16Gi", "execution_class": "local"},
                "slurm_resource_hints": {"cpu": "4", "memory": "16Gi", "walltime": "02:00:00"},
                "runtime_images": {"gatk_sif": "data/images/gatk4.sif"},
                "module_loads": ("python/3.11.9", "apptainer/1.4.1"),
            },
            supported_execution_profiles=("local", "slurm"),
            synthesis_eligible=True,
            composition_constraints=(
                "Input VCF should be joint-called (joint_call_gvcfs) or VQSR-filtered (genotype_refinement).",
                "supporting_callsets VCFs must be indexed (.tbi or .idx present).",
            ),
            pipeline_family="variant_calling",
            pipeline_stage_order=16,
        ),
        showcase_module="flytetest.tasks.variant_calling",
    ),
    # ---------------------------------------------------------------------------
    # Step 04 — Hard-filtering (new task + workflow, Milestone I)
    # ---------------------------------------------------------------------------
    RegistryEntry(
        name="variant_filtration",
        category="task",
        description=(
            "Apply GATK VariantFiltration with Best Practices hard-filtering defaults. "
            "For cohorts too small for VQSR (<30k SNPs / <2k indels). "
            "Source: https://gatk.broadinstitute.org/hc/en-us/articles/360035531112"
        ),
        inputs=(
            InterfaceField("reference_fasta", "File", "Reference genome FASTA."),
            InterfaceField("input_vcf", "File", "Joint-called cohort VCF to filter."),
            InterfaceField("mode", "str", "'SNP' or 'INDEL' — selects default filter expressions."),
            InterfaceField("cohort_id", "str", "Cohort identifier used to name the output VCF."),
            InterfaceField("filter_expressions", "list[tuple[str,str]]", "Optional override list of (filter_name, expression) tuples."),
            InterfaceField("gatk_sif", "str", "Optional Apptainer/Singularity image path for GATK4."),
        ),
        outputs=(
            InterfaceField("filtered_vcf", "File", "Hard-filtered VCF (.vcf.gz) with FILTER annotations."),
        ),
        tags=("variant_calling", "gatk4", "hard-filtering"),
        compatibility=RegistryCompatibilityMetadata(
            biological_stage="GATK4 hard-filtering (small cohort fallback)",
            accepted_planner_types=("ReferenceGenome", "VariantCallSet"),
            produced_planner_types=("VariantCallSet",),
            reusable_as_reference=False,
            execution_defaults={
                "profile": "local",
                "result_manifest": "run_manifest.json",
                "resources": {"cpu": "2", "memory": "8Gi", "execution_class": "local"},
                "slurm_resource_hints": {"cpu": "2", "memory": "8Gi", "walltime": "01:00:00"},
                "runtime_images": {"gatk_sif": "data/images/gatk4.sif"},
                "module_loads": ("python/3.11.9", "apptainer/1.4.1"),
            },
            supported_execution_profiles=("local", "slurm"),
            synthesis_eligible=True,
            composition_constraints=(
                "Filtration marks records (FILTER field) rather than removing them.",
                "Use small_cohort_filter workflow for the recommended two-pass SNP→INDEL approach.",
            ),
            pipeline_family="variant_calling",
            pipeline_stage_order=17,
        ),
        showcase_module="flytetest.tasks.variant_calling",
    ),
    # ---------------------------------------------------------------------------
    # Step 05 — QC bookend tasks (Milestone I)
    # ---------------------------------------------------------------------------
    RegistryEntry(
        name="collect_wgs_metrics",
        category="task",
        description="Picard CollectWgsMetrics + CollectInsertSizeMetrics on one coordinate-sorted BAM.",
        inputs=(
            InterfaceField("reference_fasta", "File", "Reference genome FASTA."),
            InterfaceField("aligned_bam", "File", "Coordinate-sorted, indexed BAM."),
            InterfaceField("sample_id", "str", "Sample identifier used to name output files."),
            InterfaceField("picard_sif", "str", "Optional Apptainer/Singularity image path (GATK4 SIF bundles Picard)."),
        ),
        outputs=(
            InterfaceField("wgs_metrics", "File", "WGS metrics text file from CollectWgsMetrics."),
            InterfaceField("insert_size_metrics", "File", "Insert size metrics text file from CollectInsertSizeMetrics."),
        ),
        tags=("variant_calling", "picard", "qc", "coverage"),
        compatibility=RegistryCompatibilityMetadata(
            biological_stage="Picard WGS and insert-size metrics collection",
            accepted_planner_types=("ReferenceGenome", "AlignmentSet"),
            produced_planner_types=(),
            reusable_as_reference=False,
            execution_defaults={
                "profile": "local",
                "result_manifest": "run_manifest.json",
                "resources": {"cpu": "2", "memory": "8Gi", "execution_class": "local"},
                "slurm_resource_hints": {"cpu": "4", "memory": "16Gi", "walltime": "02:00:00"},
                "runtime_images": {"picard_sif": "data/images/gatk4.sif"},
                "module_loads": ("python/3.11.9", "apptainer/1.4.1"),
            },
            supported_execution_profiles=("local", "slurm"),
            synthesis_eligible=True,
            composition_constraints=(
                "Input BAM must be coordinate-sorted and indexed.",
                "Reference has .fai and .dict present.",
            ),
            pipeline_family="variant_calling",
            pipeline_stage_order=18,
        ),
        showcase_module="flytetest.tasks.variant_calling",
    ),
    RegistryEntry(
        name="bcftools_stats",
        category="task",
        description="Run bcftools stats on a VCF/GVCF and return the stats text file.",
        inputs=(
            InterfaceField("input_vcf", "File", "Input VCF or GVCF."),
            InterfaceField("cohort_id", "str", "Cohort identifier used to name the output stats file."),
            InterfaceField("bcftools_sif", "str", "Optional Apptainer/Singularity image path for bcftools."),
        ),
        outputs=(
            InterfaceField("bcftools_stats_txt", "File", "bcftools stats output text file (MultiQC-parseable)."),
        ),
        tags=("variant_calling", "bcftools", "qc", "stats"),
        compatibility=RegistryCompatibilityMetadata(
            biological_stage="bcftools variant call statistics",
            accepted_planner_types=("VariantCallSet",),
            produced_planner_types=(),
            reusable_as_reference=False,
            execution_defaults={
                "profile": "local",
                "result_manifest": "run_manifest.json",
                "resources": {"cpu": "1", "memory": "4Gi", "execution_class": "local"},
                "slurm_resource_hints": {"cpu": "2", "memory": "8Gi", "walltime": "00:30:00"},
                "runtime_images": {"bcftools_sif": ""},
                "module_loads": ("python/3.11.9", "apptainer/1.4.1"),
            },
            supported_execution_profiles=("local", "slurm"),
            synthesis_eligible=True,
            composition_constraints=(
                "Input VCF must be valid; malformed records cause non-zero exit.",
            ),
            pipeline_family="variant_calling",
            pipeline_stage_order=19,
        ),
        showcase_module="flytetest.tasks.variant_calling",
    ),
    RegistryEntry(
        name="multiqc_summarize",
        category="task",
        description="Aggregate one or more QC tool output files into a single MultiQC HTML report.",
        inputs=(
            InterfaceField("qc_inputs", "list[File]", "QC tool output files (Picard, bcftools, FastQC, etc.)."),
            InterfaceField("cohort_id", "str", "Cohort identifier used to name the report."),
            InterfaceField("multiqc_sif", "str", "Optional Apptainer/Singularity image path for MultiQC."),
        ),
        outputs=(
            InterfaceField("multiqc_report_html", "File", "MultiQC HTML report."),
        ),
        tags=("variant_calling", "multiqc", "qc", "report"),
        compatibility=RegistryCompatibilityMetadata(
            biological_stage="MultiQC report aggregation",
            accepted_planner_types=(),
            produced_planner_types=(),
            reusable_as_reference=False,
            execution_defaults={
                "profile": "local",
                "result_manifest": "run_manifest.json",
                "resources": {"cpu": "2", "memory": "8Gi", "execution_class": "local"},
                "slurm_resource_hints": {"cpu": "2", "memory": "16Gi", "walltime": "01:00:00"},
                "runtime_images": {"multiqc_sif": ""},
                "module_loads": ("python/3.11.9", "apptainer/1.4.1"),
            },
            supported_execution_profiles=("local", "slurm"),
            synthesis_eligible=True,
            composition_constraints=(
                "MultiQC auto-detects Picard, bcftools, FastQC, GATK MarkDuplicates outputs by filename patterns.",
            ),
            pipeline_family="variant_calling",
            pipeline_stage_order=20,
        ),
        showcase_module="flytetest.tasks.variant_calling",
    ),
    # ---------------------------------------------------------------------------
    # Step 06 — SnpEff annotation (Milestone I)
    # ---------------------------------------------------------------------------
    RegistryEntry(
        name="snpeff_annotate",
        category="task",
        description=(
            "Annotate a VCF with SnpEff functional effects. "
            "SnpEff chosen for Milestone I: simpler local-SIF workflow, no ENSEMBL cache. "
            "Official docs: http://pcingola.github.io/SnpEff/"
        ),
        inputs=(
            InterfaceField("input_vcf", "File", "Input VCF to annotate."),
            InterfaceField("cohort_id", "str", "Cohort identifier used to name output files."),
            InterfaceField("snpeff_database", "str", "SnpEff database name (e.g. 'GRCh38.105', 'hg38')."),
            InterfaceField("snpeff_data_dir", "str", "Directory containing the pre-downloaded SnpEff database cache."),
            InterfaceField("snpeff_sif", "str", "Optional Apptainer/Singularity image path for SnpEff."),
        ),
        outputs=(
            InterfaceField("snpeff_vcf", "File", "SnpEff-annotated VCF."),
            InterfaceField("snpeff_genes_txt", "File", "SnpEff genes summary text file."),
        ),
        tags=("variant_calling", "snpeff", "annotation"),
        compatibility=RegistryCompatibilityMetadata(
            biological_stage="SnpEff variant functional annotation",
            accepted_planner_types=("VariantCallSet",),
            produced_planner_types=("VariantCallSet",),
            reusable_as_reference=False,
            execution_defaults={
                "profile": "local",
                "result_manifest": "run_manifest.json",
                "resources": {"cpu": "4", "memory": "16Gi", "execution_class": "local"},
                "slurm_resource_hints": {"cpu": "4", "memory": "16Gi", "walltime": "04:00:00"},
                "runtime_images": {"snpeff_sif": ""},
                "tool_databases": {"snpeff_data_dir": "data/snpeff/data"},
                "module_loads": ("python/3.11.9", "apptainer/1.4.1"),
            },
            supported_execution_profiles=("local", "slurm"),
            synthesis_eligible=True,
            composition_constraints=(
                "snpeff_data_dir must be staged on shared FS for Slurm submission.",
                "Database name must match an installed snpeff cache (e.g. GRCh38.105, hg38).",
            ),
            pipeline_family="variant_calling",
            pipeline_stage_order=21,
        ),
        showcase_module="flytetest.tasks.variant_calling",
    ),
    # ---------------------------------------------------------------------------
    # Workflow entries (unchanged from Milestone H + new Milestone I workflows)
    # ---------------------------------------------------------------------------
    RegistryEntry(
        name="prepare_reference",
        category="workflow",
        description="Prepare a reference genome for GATK germline variant calling (dict + known-sites index + BWA-MEM2 index).",
        inputs=(
            InterfaceField("reference_fasta", "File", "Reference genome FASTA."),
            InterfaceField("known_sites", "list[File]", "List of known-sites VCF Files."),
            InterfaceField("gatk_sif", "str", "Optional Apptainer/Singularity image path."),
            InterfaceField("force", "bool", "Rerun all steps even if outputs exist (default False)."),
        ),
        outputs=(
            InterfaceField("prepared_ref", "File", "Reference File (all indices in project tempdir)."),
        ),
        tags=("variant_calling", "gatk4", "reference_prep", "workflow"),
        compatibility=RegistryCompatibilityMetadata(
            biological_stage="GATK4 reference preparation",
            accepted_planner_types=("ReferenceGenome", "KnownSites"),
            produced_planner_types=("ReferenceGenome",),
            reusable_as_reference=True,
            execution_defaults={
                "profile": "local",
                "result_manifest": "run_manifest.json",
                "resources": {"cpu": "4", "memory": "16Gi", "execution_class": "local"},
                "slurm_resource_hints": {"cpu": "8", "memory": "32Gi", "walltime": "04:00:00"},
                "runtime_images": {"gatk_sif": "data/images/gatk4.sif"},
                "module_loads": ("python/3.11.9", "apptainer/1.4.1"),
            },
            supported_execution_profiles=("local", "slurm"),
            synthesis_eligible=True,
            composition_constraints=(
                "Composes create_sequence_dictionary, index_feature_file (per VCF), and bwa_mem2_index.",
            ),
            pipeline_family="variant_calling",
            pipeline_stage_order=1,
        ),
        showcase_module="flytetest.workflows.variant_calling",
    ),
    RegistryEntry(
        name="preprocess_sample",
        category="workflow",
        description="Preprocess one sample from paired-end FASTQs to BQSR-recalibrated BAM.",
        inputs=(
            InterfaceField("reference_fasta", "File", "Reference genome FASTA."),
            InterfaceField("r1", "File", "R1 FASTQ file."),
            InterfaceField("sample_id", "str", "Sample identifier."),
            InterfaceField("known_sites", "list[File]", "List of indexed known-sites VCF Files."),
            InterfaceField("r2", "File", "Optional R2 FASTQ file."),
            InterfaceField("threads", "int", "BWA-MEM2 alignment threads."),
            InterfaceField("library_id", "str", "Optional library ID for read-group."),
            InterfaceField("platform", "str", "Sequencing platform for read-group (default: ILLUMINA)."),
            InterfaceField("gatk_sif", "str", "Optional Apptainer/Singularity image path."),
        ),
        outputs=(
            InterfaceField("preprocessed_bam", "File", "BQSR-recalibrated BAM."),
        ),
        tags=("variant_calling", "gatk4", "preprocessing", "workflow"),
        compatibility=RegistryCompatibilityMetadata(
            biological_stage="GATK4 sample preprocessing",
            accepted_planner_types=("ReferenceGenome", "ReadPair", "KnownSites"),
            produced_planner_types=("AlignmentSet",),
            reusable_as_reference=True,
            execution_defaults={
                "profile": "local",
                "result_manifest": "run_manifest.json",
                "resources": {"cpu": "8", "memory": "32Gi", "execution_class": "local"},
                "slurm_resource_hints": {"cpu": "16", "memory": "64Gi", "walltime": "12:00:00"},
                "runtime_images": {"gatk_sif": "data/images/gatk4.sif"},
                "module_loads": ("python/3.11.9", "apptainer/1.4.1"),
            },
            supported_execution_profiles=("local", "slurm"),
            synthesis_eligible=True,
            composition_constraints=(
                "Reference must be prepared (prepare_reference must have run first).",
            ),
            pipeline_family="variant_calling",
            pipeline_stage_order=2,
        ),
        showcase_module="flytetest.workflows.variant_calling",
    ),
    RegistryEntry(
        name="germline_short_variant_discovery",
        category="workflow",
        description="End-to-end germline SNP and indel discovery from raw reads to joint-genotyped VCF.",
        inputs=(
            InterfaceField("reference_fasta", "File", "Reference genome FASTA."),
            InterfaceField("sample_ids", "list[str]", "Sample identifiers."),
            InterfaceField("r1_paths", "list[File]", "R1 FASTQ Files, 1:1 with sample_ids."),
            InterfaceField("known_sites", "list[File]", "Indexed known-sites VCF Files."),
            InterfaceField("intervals", "list[str]", "Genomic intervals for GenomicsDBImport."),
            InterfaceField("r2_paths", "list[File]", "Optional R2 FASTQ Files (None for single-end)."),
            InterfaceField("cohort_id", "str", "Cohort identifier."),
            InterfaceField("threads", "int", "BWA-MEM2 alignment threads."),
            InterfaceField("gatk_sif", "str", "Optional Apptainer/Singularity image path."),
        ),
        outputs=(
            InterfaceField("genotyped_vcf", "File", "Joint-genotyped VCF."),
        ),
        tags=("variant_calling", "gatk4", "joint-calling", "workflow"),
        compatibility=RegistryCompatibilityMetadata(
            biological_stage="GATK4 germline short variant discovery",
            accepted_planner_types=("ReferenceGenome", "ReadPair", "KnownSites"),
            produced_planner_types=("VariantCallSet",),
            reusable_as_reference=True,
            execution_defaults={
                "profile": "local",
                "result_manifest": "run_manifest.json",
                "resources": {"cpu": "8", "memory": "32Gi", "execution_class": "local"},
                "slurm_resource_hints": {"cpu": "16", "memory": "64Gi", "walltime": "48:00:00"},
                "runtime_images": {"gatk_sif": "data/images/gatk4.sif"},
                "module_loads": ("python/3.11.9", "apptainer/1.4.1"),
            },
            supported_execution_profiles=("local", "slurm"),
            synthesis_eligible=True,
            composition_constraints=(
                "Reference must be prepared (prepare_reference must have run first).",
                "Per-sample loop is synchronous; no asyncio.gather.",
                "At least one genomic interval is required for GenomicsDBImport.",
            ),
            pipeline_family="variant_calling",
            pipeline_stage_order=3,
        ),
        showcase_module="flytetest.workflows.variant_calling",
    ),
    RegistryEntry(
        name="genotype_refinement",
        category="workflow",
        description="Refine a joint-called VCF with two-pass VQSR (SNP then INDEL) using GATK4.",
        inputs=(
            InterfaceField("reference_fasta", "File", "Reference genome FASTA."),
            InterfaceField("joint_vcf", "File", "Joint-called cohort VCF."),
            InterfaceField("snp_resources", "list[File]", "VCF Files for SNP VQSR training."),
            InterfaceField("snp_resource_flags", "list[dict]", "Parallel per-resource flag dicts for SNP pass."),
            InterfaceField("indel_resources", "list[File]", "VCF Files for INDEL VQSR training."),
            InterfaceField("indel_resource_flags", "list[dict]", "Parallel per-resource flag dicts for INDEL pass."),
            InterfaceField("cohort_id", "str", "Cohort identifier used to name output files."),
            InterfaceField("sample_count", "int", "Number of samples in the cohort (used for InbreedingCoeff auto-add)."),
            InterfaceField("snp_filter_level", "float", "SNP truth-sensitivity filter level (0.0 = default 99.5)."),
            InterfaceField("indel_filter_level", "float", "INDEL truth-sensitivity filter level (0.0 = default 99.0)."),
            InterfaceField("gatk_sif", "str", "Optional Apptainer/Singularity image path."),
        ),
        outputs=(
            InterfaceField("refined_vcf", "File", "VQSR-refined VCF after both passes."),
        ),
        tags=("variant_calling", "gatk4", "vqsr", "workflow"),
        compatibility=RegistryCompatibilityMetadata(
            biological_stage="GATK4 two-pass VQSR genotype refinement",
            accepted_planner_types=("ReferenceGenome", "VariantCallSet", "KnownSites"),
            produced_planner_types=("VariantCallSet",),
            reusable_as_reference=True,
            execution_defaults={
                "profile": "local",
                "result_manifest": "run_manifest.json",
                "resources": {"cpu": "8", "memory": "32Gi", "execution_class": "local"},
                "slurm_resource_hints": {"cpu": "8", "memory": "32Gi", "walltime": "08:00:00"},
                "runtime_images": {"gatk_sif": "data/images/gatk4.sif"},
                "module_loads": ("python/3.11.9", "apptainer/1.4.1"),
            },
            supported_execution_profiles=("local", "slurm"),
            synthesis_eligible=True,
            composition_constraints=(
                "Requires a joint-called VCF with sufficient variant count for VQSR training "
                "(chr20 slice is too small; use full chr20 WGS at ≥30x).",
                "INDEL pass consumes the SNP-filtered VCF; pass ordering is mandatory.",
            ),
            pipeline_family="variant_calling",
            pipeline_stage_order=4,
        ),
        showcase_module="flytetest.workflows.variant_calling",
    ),
    RegistryEntry(
        name="preprocess_sample_from_ubam",
        category="workflow",
        description="Preprocess one sample via the uBAM path: align, merge with uBAM, dedup, and BQSR-recalibrate.",
        inputs=(
            InterfaceField("reference_fasta", "File", "Reference genome FASTA."),
            InterfaceField("r1", "File", "R1 FASTQ file."),
            InterfaceField("ubam", "File", "Queryname-sorted unmapped BAM."),
            InterfaceField("sample_id", "str", "Sample identifier."),
            InterfaceField("known_sites", "list[File]", "List of indexed known-sites VCF Files."),
            InterfaceField("r2", "File", "Optional R2 FASTQ file."),
            InterfaceField("threads", "int", "BWA-MEM2 alignment threads."),
            InterfaceField("library_id", "str", "Optional library ID for read-group."),
            InterfaceField("platform", "str", "Sequencing platform for read-group (default: ILLUMINA)."),
            InterfaceField("gatk_sif", "str", "Optional Apptainer/Singularity image path."),
        ),
        outputs=(
            InterfaceField("preprocessed_bam_from_ubam", "File", "BQSR-recalibrated BAM produced via the uBAM path."),
        ),
        tags=("variant_calling", "gatk4", "preprocessing", "workflow", "ubam"),
        compatibility=RegistryCompatibilityMetadata(
            biological_stage="GATK4 sample preprocessing via uBAM path",
            accepted_planner_types=("ReferenceGenome", "ReadPair", "UnmappedBAM", "KnownSites"),
            produced_planner_types=("AlignmentSet",),
            reusable_as_reference=True,
            execution_defaults={
                "profile": "local",
                "result_manifest": "run_manifest.json",
                "resources": {"cpu": "8", "memory": "32Gi", "execution_class": "local"},
                "slurm_resource_hints": {"cpu": "16", "memory": "64Gi", "walltime": "04:00:00"},
                "runtime_images": {"gatk_sif": "data/images/gatk4.sif"},
                "module_loads": ("python/3.11.9", "apptainer/1.4.1"),
            },
            supported_execution_profiles=("local", "slurm"),
            synthesis_eligible=True,
            composition_constraints=(
                "ubam must be queryname-sorted.",
                "No sort_sam step — MergeBamAlignment --SORT_ORDER coordinate handles sorting.",
                "Reference must be prepared (prepare_reference must have run first).",
            ),
            pipeline_family="variant_calling",
            pipeline_stage_order=5,
        ),
        showcase_module="flytetest.workflows.variant_calling",
    ),
    RegistryEntry(
        name="sequential_interval_haplotype_caller",
        category="workflow",
        description=(
            "Call per-sample GVCFs serially across genomic intervals, then gather into a single GVCF. "
            "Execution is synchronous inside one task invocation; real scatter (job arrays) is Milestone K."
        ),
        inputs=(
            InterfaceField("reference_fasta", "File", "Reference genome FASTA."),
            InterfaceField("aligned_bam", "File", "BQSR-recalibrated BAM."),
            InterfaceField("sample_id", "str", "Sample identifier."),
            InterfaceField("intervals", "list[str]", "Non-empty list of genomic intervals in genomic order."),
            InterfaceField("gatk_sif", "str", "Optional Apptainer/Singularity image path."),
        ),
        outputs=(
            InterfaceField("scattered_gvcf", "File", "Gathered per-sample GVCF."),
        ),
        tags=("variant_calling", "gatk4", "gvcf", "scatter-gather", "workflow"),
        compatibility=RegistryCompatibilityMetadata(
            biological_stage="GATK4 interval-sequential HaplotypeCaller with gather",
            accepted_planner_types=("ReferenceGenome", "AlignmentSet"),
            produced_planner_types=("VariantCallSet",),
            reusable_as_reference=True,
            execution_defaults={
                "profile": "local",
                "result_manifest": "run_manifest.json",
                "resources": {"cpu": "16", "memory": "64Gi", "execution_class": "local"},
                "slurm_resource_hints": {"cpu": "16", "memory": "64Gi", "walltime": "24:00:00"},
                "runtime_images": {"gatk_sif": "data/images/gatk4.sif"},
                "module_loads": ("python/3.11.9", "apptainer/1.4.1"),
            },
            supported_execution_profiles=("local", "slurm"),
            synthesis_eligible=True,
            composition_constraints=(
                "intervals must be non-empty and in genomic order for GatherVcfs.",
                "Execution is synchronous — all intervals run serially inside one task invocation. "
                "True scheduler-level scatter (job arrays or per-interval sbatch fan-out) is Milestone K HPC work.",
                "BAM must be BQSR-recalibrated (preprocess_sample or preprocess_sample_from_ubam must have run first).",
            ),
            pipeline_family="variant_calling",
            pipeline_stage_order=6,
        ),
        showcase_module="flytetest.workflows.variant_calling",
    ),
    RegistryEntry(
        name="post_genotyping_refinement",
        category="workflow",
        description="Apply CalculateGenotypePosteriors to a joint-called or VQSR-filtered cohort VCF.",
        inputs=(
            InterfaceField("input_vcf", "File", "Input VCF (joint-called or VQSR-filtered)."),
            InterfaceField("cohort_id", "str", "Cohort identifier used to name the output VCF."),
            InterfaceField("supporting_callsets", "list[File]", "Optional list of population VCF Files for prior refinement."),
            InterfaceField("gatk_sif", "str", "Optional Apptainer/Singularity image path."),
        ),
        outputs=(
            InterfaceField("refined_vcf_cgp", "File", "CGP-refined cohort VCF (.vcf.gz)."),
        ),
        tags=("variant_calling", "gatk4", "cgp", "genotype-refinement", "workflow"),
        compatibility=RegistryCompatibilityMetadata(
            biological_stage="GATK4 post-genotyping refinement via CalculateGenotypePosteriors",
            accepted_planner_types=("VariantCallSet",),
            produced_planner_types=("VariantCallSet",),
            reusable_as_reference=True,
            execution_defaults={
                "profile": "local",
                "result_manifest": "run_manifest.json",
                "resources": {"cpu": "4", "memory": "16Gi", "execution_class": "local"},
                "slurm_resource_hints": {"cpu": "4", "memory": "16Gi", "walltime": "02:00:00"},
                "runtime_images": {"gatk_sif": "data/images/gatk4.sif"},
                "module_loads": ("python/3.11.9", "apptainer/1.4.1"),
            },
            supported_execution_profiles=("local", "slurm"),
            synthesis_eligible=True,
            composition_constraints=(
                "Composable after genotype_refinement (VQSR) or directly after joint_call_gvcfs.",
                "supporting_callsets VCFs must be indexed when provided.",
            ),
            pipeline_family="variant_calling",
            pipeline_stage_order=7,
        ),
        showcase_module="flytetest.workflows.variant_calling",
    ),
    # ---------------------------------------------------------------------------
    # Step 04 — small_cohort_filter workflow (Milestone I)
    # ---------------------------------------------------------------------------
    RegistryEntry(
        name="small_cohort_filter",
        category="workflow",
        description=(
            "Hard-filter a joint-called VCF with separate SNP and INDEL passes "
            "(GATK Best Practices defaults). Intended for cohorts too small for VQSR "
            "(<30k SNPs / <2k indels). Mirrors the two-pass structure of genotype_refinement."
        ),
        inputs=(
            InterfaceField("reference_fasta", "File", "Reference genome FASTA."),
            InterfaceField("joint_vcf", "File", "Joint-called cohort VCF to filter."),
            InterfaceField("cohort_id", "str", "Cohort identifier."),
            InterfaceField("snp_filter_expressions", "list[tuple[str,str]]", "Optional override SNP filter expressions."),
            InterfaceField("indel_filter_expressions", "list[tuple[str,str]]", "Optional override INDEL filter expressions."),
            InterfaceField("gatk_sif", "str", "Optional Apptainer/Singularity image path."),
        ),
        outputs=(
            InterfaceField("small_cohort_filtered_vcf", "File", "Hard-filtered VCF after SNP then INDEL passes."),
        ),
        tags=("variant_calling", "gatk4", "hard-filtering", "workflow"),
        compatibility=RegistryCompatibilityMetadata(
            biological_stage="GATK4 small-cohort hard-filtering",
            accepted_planner_types=("ReferenceGenome", "VariantCallSet"),
            produced_planner_types=("VariantCallSet",),
            reusable_as_reference=True,
            execution_defaults={
                "profile": "local",
                "result_manifest": "run_manifest.json",
                "resources": {"cpu": "2", "memory": "8Gi", "execution_class": "local"},
                "slurm_resource_hints": {"cpu": "2", "memory": "8Gi", "walltime": "01:00:00"},
                "runtime_images": {"gatk_sif": "data/images/gatk4.sif"},
                "module_loads": ("python/3.11.9", "apptainer/1.4.1"),
            },
            supported_execution_profiles=("local", "slurm"),
            synthesis_eligible=True,
            composition_constraints=(
                "For cohorts with <30k SNPs or <2k indels where VQSR training fails.",
            ),
            pipeline_family="variant_calling",
            pipeline_stage_order=8,
        ),
        showcase_module="flytetest.workflows.variant_calling",
    ),
    # ---------------------------------------------------------------------------
    # Step 05 — QC bookend workflows (Milestone I)
    # ---------------------------------------------------------------------------
    RegistryEntry(
        name="pre_call_coverage_qc",
        category="workflow",
        description="Per-sample Picard WGS + insert-size metrics aggregated into one MultiQC report.",
        inputs=(
            InterfaceField("reference_fasta", "File", "Reference genome FASTA."),
            InterfaceField("aligned_bams", "list[File]", "Coordinate-sorted, indexed BAMs."),
            InterfaceField("sample_ids", "list[str]", "Sample identifiers, 1:1 with aligned_bams."),
            InterfaceField("cohort_id", "str", "Cohort identifier."),
            InterfaceField("picard_sif", "str", "Optional SIF for Picard."),
            InterfaceField("multiqc_sif", "str", "Optional SIF for MultiQC."),
        ),
        outputs=(
            InterfaceField("pre_call_qc_bundle", "File", "MultiQC HTML report aggregating per-sample QC."),
        ),
        tags=("variant_calling", "picard", "multiqc", "qc", "workflow"),
        compatibility=RegistryCompatibilityMetadata(
            biological_stage="Pre-call coverage QC aggregation",
            accepted_planner_types=("ReferenceGenome", "AlignmentSet"),
            produced_planner_types=(),
            reusable_as_reference=True,
            execution_defaults={
                "profile": "local",
                "result_manifest": "run_manifest.json",
                "resources": {"cpu": "4", "memory": "16Gi", "execution_class": "local"},
                "slurm_resource_hints": {"cpu": "4", "memory": "16Gi", "walltime": "04:00:00"},
                "runtime_images": {"picard_sif": "data/images/gatk4.sif", "multiqc_sif": ""},
                "module_loads": ("python/3.11.9", "apptainer/1.4.1"),
            },
            supported_execution_profiles=("local", "slurm"),
            synthesis_eligible=True,
            composition_constraints=(
                "All BAMs must be coordinate-sorted and indexed.",
                "does not produce pipeline-state planner types; outputs are QC artifacts only.",
            ),
            pipeline_family="variant_calling",
            pipeline_stage_order=9,
        ),
        showcase_module="flytetest.workflows.variant_calling",
    ),
    RegistryEntry(
        name="post_call_qc_summary",
        category="workflow",
        description="bcftools stats + MultiQC for post-call VCF QC; optional extra_qc_files merges additional tool logs.",
        inputs=(
            InterfaceField("input_vcf", "File", "Input VCF for bcftools stats."),
            InterfaceField("cohort_id", "str", "Cohort identifier."),
            InterfaceField("extra_qc_files", "list[File]", "Optional extra QC files to include in MultiQC."),
            InterfaceField("bcftools_sif", "str", "Optional SIF for bcftools."),
            InterfaceField("multiqc_sif", "str", "Optional SIF for MultiQC."),
        ),
        outputs=(
            InterfaceField("post_call_qc_bundle", "File", "MultiQC HTML report aggregating post-call QC."),
        ),
        tags=("variant_calling", "bcftools", "multiqc", "qc", "workflow"),
        compatibility=RegistryCompatibilityMetadata(
            biological_stage="Post-call QC summary",
            accepted_planner_types=("VariantCallSet",),
            produced_planner_types=(),
            reusable_as_reference=True,
            execution_defaults={
                "profile": "local",
                "result_manifest": "run_manifest.json",
                "resources": {"cpu": "2", "memory": "8Gi", "execution_class": "local"},
                "slurm_resource_hints": {"cpu": "2", "memory": "8Gi", "walltime": "01:00:00"},
                "runtime_images": {"bcftools_sif": "", "multiqc_sif": ""},
                "module_loads": ("python/3.11.9", "apptainer/1.4.1"),
            },
            supported_execution_profiles=("local", "slurm"),
            synthesis_eligible=True,
            composition_constraints=(
                "Input VCF must be valid for bcftools stats.",
                "does not produce pipeline-state planner types; outputs are QC artifacts only.",
            ),
            pipeline_family="variant_calling",
            pipeline_stage_order=10,
        ),
        showcase_module="flytetest.workflows.variant_calling",
    ),
    # ---------------------------------------------------------------------------
    # Step 06 — annotate_variants_snpeff workflow (Milestone I)
    # ---------------------------------------------------------------------------
    RegistryEntry(
        name="annotate_variants_snpeff",
        category="workflow",
        description="Thin wrapper: annotate a VCF with SnpEff and return the annotated VCF.",
        inputs=(
            InterfaceField("input_vcf", "File", "Input VCF to annotate."),
            InterfaceField("cohort_id", "str", "Cohort identifier."),
            InterfaceField("snpeff_database", "str", "SnpEff database name (e.g. 'GRCh38.105', 'hg38')."),
            InterfaceField("snpeff_data_dir", "str", "Directory containing the pre-downloaded SnpEff database cache."),
            InterfaceField("snpeff_sif", "str", "Optional Apptainer/Singularity image path for SnpEff."),
        ),
        outputs=(
            InterfaceField("annotated_vcf", "File", "SnpEff-annotated VCF."),
        ),
        tags=("variant_calling", "snpeff", "annotation", "workflow"),
        compatibility=RegistryCompatibilityMetadata(
            biological_stage="SnpEff variant functional annotation workflow",
            accepted_planner_types=("VariantCallSet",),
            produced_planner_types=("VariantCallSet",),
            reusable_as_reference=True,
            execution_defaults={
                "profile": "local",
                "result_manifest": "run_manifest.json",
                "resources": {"cpu": "4", "memory": "16Gi", "execution_class": "local"},
                "slurm_resource_hints": {"cpu": "4", "memory": "16Gi", "walltime": "04:00:00"},
                "runtime_images": {"snpeff_sif": ""},
                "tool_databases": {"snpeff_data_dir": "data/snpeff/data"},
                "module_loads": ("python/3.11.9", "apptainer/1.4.1"),
            },
            supported_execution_profiles=("local", "slurm"),
            synthesis_eligible=True,
            composition_constraints=(
                "snpeff_data_dir must be staged on shared FS for Slurm submission.",
            ),
            pipeline_family="variant_calling",
            pipeline_stage_order=11,
        ),
        showcase_module="flytetest.workflows.variant_calling",
    ),
)
