#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
# PASA image smoke workspace on the host checkout.
PASA_IMAGE_SMOKE_ROOT="${PASA_IMAGE_SMOKE_ROOT:-$REPO_ROOT/temp/minimal_pasa_image_smoke}"
# PASA work directory that should contain the image-backed outputs.
HOST_PASA_WORK_DIR="${HOST_PASA_WORK_DIR:-$PASA_IMAGE_SMOKE_ROOT/pasa}"
# Staged transcript FASTA used as the image-backed PASA input.
STAGED_TRANSCRIPTS_FASTA="${STAGED_TRANSCRIPTS_FASTA:-}"
# Staged genome FASTA used by the image-backed smoke.
STAGED_GENOME_FASTA="${STAGED_GENOME_FASTA:-}"
# PASA config generated by the image smoke helper.
HOST_PASA_CONFIG="${HOST_PASA_CONFIG:-$HOST_PASA_WORK_DIR/config/alignAssembly.conf}"
# PASA image used by the smoke.
PASA_SIF="${PASA_SIF:-$REPO_ROOT/data/images/pasa_2.5.3.sif}"

require_file() {
  local path="$1"
  [[ -f "$path" ]] || {
    echo "missing file: $path" >&2
    exit 1
  }
  [[ -s "$path" ]] || {
    echo "empty file: $path" >&2
    exit 1
  }
}

require_dir() {
  local path="$1"
  [[ -d "$path" ]] || {
    echo "missing directory: $path" >&2
    exit 1
  }
}

find_unique_file() {
  local root="$1"
  local pattern="$2"
  local matches
  shopt -s nullglob
  matches=("$root"/$pattern)
  shopt -u nullglob
  if [[ ${#matches[@]} -eq 1 && -f "${matches[0]}" ]]; then
    printf '%s\n' "${matches[0]}"
    return 0
  fi
  return 1
}

find_output_file() {
  local root="$1"
  local pattern="$2"
  local candidate
  candidate="$(find "$root" -type f -name "$pattern" | sort | head -n 1)"
  if [[ -n "$candidate" ]]; then
    printf '%s\n' "$candidate"
    return 0
  fi
  return 1
}

require_dir "$HOST_PASA_WORK_DIR"
STAGED_TRANSCRIPTS_FASTA="$(find_unique_file "$HOST_PASA_WORK_DIR/transcripts" '*.fasta' || true)"
if [[ -z "$STAGED_TRANSCRIPTS_FASTA" ]]; then
  echo "missing staged transcript FASTA under: $HOST_PASA_WORK_DIR/transcripts" >&2
  exit 1
fi
STAGED_GENOME_FASTA="$(find_unique_file "$HOST_PASA_WORK_DIR/reference" '*.fa' || true)"
if [[ -z "$STAGED_GENOME_FASTA" ]]; then
  echo "missing staged genome FASTA under: $HOST_PASA_WORK_DIR/reference" >&2
  exit 1
fi
require_file "$HOST_PASA_CONFIG"
require_file "$PASA_SIF"

PASA_ASSEMBLIES_GFF3="$(find_output_file "$HOST_PASA_WORK_DIR" '*.pasa_assemblies.gff3' || true)"
if [[ -z "$PASA_ASSEMBLIES_GFF3" ]]; then
  PASA_ASSEMBLIES_GFF3="$(find_output_file "$HOST_PASA_WORK_DIR" '*.assemblies.gff3' || true)"
fi
PASA_ASSEMBLIES_FASTA="$(find_output_file "$HOST_PASA_WORK_DIR" '*.assemblies.fasta' || true)"
PASA_ASSEMBLIES_GTF="$(find_output_file "$HOST_PASA_WORK_DIR" '*.pasa_assemblies.gtf' || true)"
if [[ -z "$PASA_ASSEMBLIES_GTF" ]]; then
  PASA_ASSEMBLIES_GTF="$(find_output_file "$HOST_PASA_WORK_DIR" '*.assemblies.gtf' || true)"
fi

if [[ -z "$PASA_ASSEMBLIES_GFF3" ]]; then
  echo "missing PASA assemblies GFF3 under: $HOST_PASA_WORK_DIR" >&2
  exit 1
fi
if [[ -z "$PASA_ASSEMBLIES_FASTA" ]]; then
  echo "missing PASA assemblies FASTA under: $HOST_PASA_WORK_DIR" >&2
  exit 1
fi
if [[ -z "$PASA_ASSEMBLIES_GTF" ]]; then
  echo "missing PASA assemblies GTF under: $HOST_PASA_WORK_DIR" >&2
  exit 1
fi

echo "minimal PASA image smoke artifacts are present"
echo "trinity fasta: $STAGED_TRANSCRIPTS_FASTA"
echo "genome fasta: $STAGED_GENOME_FASTA"
echo "pasa config: $HOST_PASA_CONFIG"
echo "pasa image: $PASA_SIF"
echo "pasa assemblies gff3: $PASA_ASSEMBLIES_GFF3"
echo "pasa assemblies fasta: $PASA_ASSEMBLIES_FASTA"
echo "pasa assemblies gtf: $PASA_ASSEMBLIES_GTF"
